### DISCUSSION TITLE
Generate entrypoint

### DISCUSSION THREAD

**Discussion by ademenet** [obsidian-html/obsidian-html#337] [Q&A]
Hi!

First: this is a great project! Thank you for sharing it to the community.

I have trouble to find if it is possible to avoid to mention an markdown entrypoint.

It seems to be possible but I am unable to make it work. I did:

```yaml
obsidian_folder_path_str: "/my/path/"
toggles:
  compile_md: False
  features:
    create_index_from_dir_structure:
      enabled: True
      rel_output_path: "index.html"
      styling:
        show_icon: True
      exclude_subfolders:
        - ".git"
        - "__src"
        - "md"
        - "obs.html"
      exclude_files:
        - "favicon.ico"
        - "not_created.html"
```

But it complains `Key "obsidian_entrypoint_path_str" is required.` even if I used `compile_md: False`. I followed [this page](https://obsidian-html.github.io/Configurations/Create%20Index%20from%20Directory%20Structure.html).

What am I doing wrong? Thank you!
