### DISCUSSION TITLE
Does anyone have it working to publish via a github action?

### DISCUSSION THREAD

**Discussion by katylava** [obsidian-html/obsidian-html#767] [Q&A] [answered]
I have a vault I'm testing with which has about 70 markdown files, over half of which are empty. When I use `obsidianhtml` on my computer it works beautifully. When I try the documented [github action](https://obsidian-html.github.io/automation/automate-website-deployment.html#!using-github-pages) it hangs. I've tried several times and let it run 15-20 minutes before cancelling it.

My github action file is as follows:

```yaml
name: Publish to gh-pages branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: clone-path

      - name: Install dependencies and run build
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install obsidianhtml
          obsidianhtml convert -i clone-path/.publish/config.yml -v
          touch html/.nojekyll

      - name: Publish to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: html # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
```

...the only thing I changed from the documented github action is the path to the config file, which I keep at `.publish/config.yml` in my main branch. Oh I also changed it so it's installing the `obsidianhtml` version on PYPI, not the development version.

My config.yml file looks like this:

```yaml
obsidian_entrypoint_path_str: "clone-path/README.md"
exclude_glob:
  - "/.obsidian"
  - "/.trash"
  - "/.DS_Store"
  - "/.git"
  - "/.publish"
toggles:
  process_all: True
  features:
    table_of_contents:
      add_toc_when_missing: True
```

In the logs, there is no output after the final `pip install` line `Successfully installed appdirs-1.4.4 beautifulsoup4-4.12.3 bottle-0.12.25 html5lib-1.1 lxml-5.1.0 markdown-3.5.2 obsidianhtml-3.5.2 proxy-tools-0.1.0 pymdown-extensions-10.7 python-frontmatter-1.1.0 pywebview-4.4.1 regex-2023.12.25 soupsieve-2.5 typing-extensions-4.9.0 webencodings-0.5.1 whoosh-2.7.4`. So it seems to be hanging on `obsidianhtml convert...` with no output.

**Comment by katylava** [comment]
I think it's because I'm not commiting the `.obsidian` folder since it's a shared vault ☹️ .

> The value will be determined instead by opening the folder that [obsidian_entrypoint_path_str](https://obsidian-html.github.io/configurations/configuration-options.html#obsidian_entrypoint_path_str) is in, looking for a folder called .obsidian and going one folder up if not found, until found.

https://obsidian-html.github.io/configurations/deprecated-configurations/obsidian_folder_path_str.html

**Reply by dwrolvink** [reply]
I'm a bit late to the party, but for others reading this discussion, there is also a section on using a subfolder within a vault (which you seem to be doing here?) on this page, going into a bit more detail:
- https://obsidian-html.github.io/instructions/tutorials/converting-just-one-subfolder-in-your-vault.html

**Reply by katylava** [reply]
Oh that will be helpful too because we might keep everything in a `docs` folder. If attachments are outside of that subfolder do you know if it breaks them? Our structure is like:

```
❧ tree -L 2
.
├── DEMO.md
├── Obsidian
│   ├── Obsidian Devdocs ADR (WIP).md
│   ├── Obsidian Experiment Notes.md
│   ├── Recommended Settings.md
│   ├── Transclusion
│   └── Using Obsidian.md
├── README.md
├── Writing Documentation.md
├── docs
│   ├── Explanation
│   ├── Guides
│   ├── Reference
│   └── Tutorials
└── imgs
    ├── filter-backlinks.png
    └── four-doc-types-explanation.png
```

So if a file under `docs` referenced an image under `imgs` do you know if that image would be visible or broken in the html output?

Oh and the reason there was no `.obsidian` folder in my repo is not because it's a subfolder, but because we are testing out using Obsidian internally for our developer documentation, and we would want people to be able to customize Obsidian for themselves, so `.obsidian` is in the `.gitignore` file.

**Reply by dwrolvink** [reply]
If I understand you correctly, you want to export everything under `/Obisidian`. Notes there will have links to notes under `/docs` and those might use images from `/imgs`. 

In that case I'd opt for just having the `.obsidian` folder be placed in the root and then selectively include and/or exclude folders using:
- https://obsidian-html.github.io/configurations/modules/get-file-list.html

**Comment by katylava** [comment, marked as answer]
Ok here is a working version that adds an empty `.obsidian` directory to the root of clone-path:

```
name: Publish to gh-pages branch
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: clone-path

      - name: Install dependencies and run build
        run: |
          cd ${{ github.workspace }}
          pip install --upgrade pip
          pip install obsidianhtml
          mkdir clone-path/.obsidian # this folder needs to exist so obsidianhtml can find the root of the vault
          obsidianhtml convert -i clone-path/.publish/config.yml -v
          touch output/html/.nojekyll

      - name: Publish to Github Pages
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages # The branch name where you want to push the assets
          FOLDER: output/html # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
```

Also I'm using the default output path so I had to change `html` to `output/html`.
