### DISCUSSION TITLE
(How) Can one convert multiple notes by combining `include_glob` and `exclude_glob` and setting `process_all=True`?

### DISCUSSION THREAD

**Discussion by Gewerd-Strauss** [obsidian-html/obsidian-html#776] [General]
Hello,

a question:

Currently I have the predicament that I must run ObsidianHTML on multiple files, and for doing so I must re-run my own script each time.

This takes quite some time; of which the vast majority is attributed to the OHTML, along its pre-/post-processing (dynamically limiting the vault by inserting a temporary `.obsidian`-folder,generating the unique config file for OHTML, calling OHTML, removing the vault-limiter):

```txt
Timings:

ObsidianHTML              > 28.10.2024 - 11:08:24
ObsidianHTML              < 28.10.2024 - 11:09:13
                                           00:00:49.516
intermediary Processing   > 28.10.2024 - 11:09:13
intermediary Processing   < 28.10.2024 - 11:09:14
                                           00:00:00.625
Compilation               > 28.10.2024 - 11:09:14
Compilation               < 28.10.2024 - 11:09:14
                                         00:00:00.516

Total (not ms-precise)                   00:00:50.657
```

Obviously this is technically outside the scope of OHTML.

These steps must be performed for each note manually currently - and this is generally good so.
However, the configurations of the calls to OHTML only differ in the note they convert.

I am not sure if this is possible, but below I outline what I believe would be a more efficient method to approach the above issue - and the question is if ohtml's configuration-options allow for that.

- set `toggles.process_all` to `true`, 
- do not set `obsidian_entrypoint_path_str` (or set it to vault's root, idk)
- use `module_config.get_file_list.include_glob` 
   - to add the absolute paths to the desired notes, e.g. instead of 
   
```yaml
obsidian_entrypoint_path_str: 'D:\Dokumente neu\Obsidian NoteTaking\BE31-Thesis-quarto\report\___manuscript_restruct.md'
# module_data_folder: 'output/mod'
max_note_depth: 15
# preserve_inline_tags: False
copy_vault_to_tempdir: True

module_config:
  get_file_list:
    include_glob:
      value: '*'
    exclude_glob:
      value:
        - "/.git/**/*"
        - "/.github/**/*"
        - "/.obsidian/**/*"
        - "/.quarto/**/*"
        - "/.renv/**/*"
        - "/.Rproj.user/**/*"
        - "/.trash/**/*"
        - "/.vscode/**/*"
        - "/002 templates/**/*"
        - "/_freeze/**/*"
        - "/_site/**/*"
        - "/.DS_Store/**/*"


```

do the following

```yml
obsidian_entrypoint_path_str: '.'  # not sure what this would have to be set to
# module_data_folder: 'output/mod'
max_note_depth: 15
# preserve_inline_tags: False
copy_vault_to_tempdir: True

module_config:
  get_file_list:
    include_glob:
      value:
        - 'D:\Dokumente neu\Obsidian NoteTaking\BE31-Thesis-quarto\report\___manuscript_restruct.md'
        - 'D:\Dokumente neu\Obsidian NoteTaking\BE31-Thesis-quarto\report\___manuscript.md'
        - 'D:\Dokumente neu\Obsidian NoteTaking\BE31-Thesis-quarto\report\___manuscript_outline.md'
    exclude_glob:
      value:
        - "/.git/**/*"
        - "/.github/**/*"
        - "/.obsidian/**/*"
        - "/.quarto/**/*"
        - "/.renv/**/*"
        - "/.Rproj.user/**/*"
        - "/.trash/**/*"
        - "/.vscode/**/*"
        - "/002 templates/**/*"
        - "/_freeze/**/*"
        - "/_site/**/*"
        - "/.DS_Store/**/*"

toggles:
  process_all=true # not sure if this is the correct key/location for it, from memory
```

In principal, this could then allow me to convert multiple notes without re-launching OHTML every time, and without re-creating a new config-yml for it each time.

There however are a couple of questions:

1. Is this even possible to begin with? That is, would something like the above cause only the `include_glob`'d notes to be parsed, their embeds be parsed and inserted, and the converted md-files be generated? 
2. Given we set `copy_vault_to_tempdir` to `True`, how would the output be structured? Since we have multiple output notes, we couldn't have a single output named `index.md` located at `<obsidian-htm-python-module>\output\md`, e.g. `D:\Dokumente neu\Repositories\python\obsidian-html\output\md\`. How would the `output\md`-directory be structured? How could it be structured such that one could re-map the generated md-files to the location of their input targets?
    1. Would the std-output give information on the structure? E.g. would we get an overview on which input mapped to which output, so that post-processing can move them to the correct places, instead of the following? 
    
    ```yml
      > COMPILING MARKDOWN FROM OBSIDIAN CODE (C:\Users\Claudius Main\AppData\Local\obsidianhtml\obsidianhtml\tmpdir\input\report\___manuscript_restruct.md)
      > COMPILING HTML FROM MARKDOWN CODE (D:\Dokumente neu\Repositories\python\obsidian-html\output\md\index.md)
	      > COMPILING INDEX FROM DIR STRUCTURE (D:\Dokumente neu\Repositories\python\obsidian-html\output\html\obs.html\dir_index.html)
	      < COMPILING INDEX FROM DIR STRUCTURE: Done
	      > SECOND PASS HTML
	      < SECOND PASS HTML: Done
      < COMPILING HTML FROM MARKDOWN CODE: Done
      
      You can find your output at:
	      md: D:\Dokumente neu\Repositories\python\obsidian-html\output\md
	      html: D:\Dokumente neu\Repositories\python\obsidian-html\output\html
    ```
    
If the above is possible, I could in theory save the overhead of preparing the unique config-files for successive calls to OHTML, and more importantly convert them all in a single call to my wrapper program, instead of running that for each note separately.
