### ISSUE TITLE
Links within note inclusions are considered external.

### ISSUE THREAD

**Issue by Krrrrrrk** [obsidian-html/obsidian-html#178]
Love the work here. I apologize if I'm missing an option, but from my tests links to other notes within note inclusions are considered external, which prevents the .md files linked in the note inclusion being converted to .html unless Process All is enabled. This may break the path in the URL as well. 

For example:

NoteA:
![NoteB]

If NoteB has links to other notes, those don't get converted to .html

**Comment by dwrolvink** [comment]
Hi, thanks for trying the package and letting me know you're having an issue!

I can't replicate the error as of yet. 

The example code does not work for me, neither in Obsidian, nor does it get changed by ObsidianHtml. I've used `![[NoteB]]` for testing instead. This works as expected: it does not give me any link, just the contents of NoteB in NoteA.

There are a couple of quick checks that you can try:
- Are all the notes in the folder configured at `obsidian_folder_path_str` in the config yaml? (Any note outside that folder will be considered external by default)
- Does the link to the note work if you make it a normal link, or is it still an external link then?
- Does the name of the note contain '://` anywhere? 
- Can you change the filename to something containing only alphanumeric characters (like actually `NoteB`), does it work then?
- What does the output tell you when you append `-v` to the command that you run to generate the website? (e.g. `obsidianhtml -i config.yml -v`
 

If that leads nowhere, maybe you can share a bit more in depth information here:

- What is the version that you are using? (try `pip show obsidianhtml`)
- What are the contents of the config.yaml that you use?
- Can you share the verbose output?
- Can you create two test notes (one source linking to the second), test that they also have the issue, send their contents here and their filenames/paths?

Once I have a setup that contains the bug I can work on a way to correct it.

**Comment by dwrolvink** [comment]
Also curious what would happen if you add 
``` yaml
toggles:
    # Whether external http anchor links should have a target of "_blank"
  external_blank: False  
```

to your config.yml, if that would do anything
(but your inclusion being parsed as a link, instead of dumping the content is the real issue here I guess)

**Comment by dwrolvink** [comment]
Wow, sorry for the spam, but I just read your question entirely wrong. 

I just created the same setup:
```
# noteA
![[noteB]]
```
```
# noteB
[[noteC]]
```
```
# noteC
test
```

This works fine, in noteA I have the code of noteB and that links to noteC.html, no external links, it all works. This with the following config:

``` yaml
# The first folder that contains all obsidian files
obsidian_folder_path_str: 'ci/test_vault/'

# The note that will be used as the index.html 
obsidian_entrypoint_path_str: 'ci/test_vault/entrypoint.md'

# Input and output path of markdown files
md_folder_path_str:  'tmp/md'

# Markdown entrypoint path
md_entrypoint_path_str: 'tmp/md/index.md'

# Output path of HTML files
html_output_folder_path_str: 'tmp/html'

toggles:
    # Whether external http anchor links should have a target of "_blank"
  external_blank: False  
  # Opt-in/-out of Obsidian->Md conversion, set to False when using proper markdown as input
  compile_md: True

  # Opt-in/-out of Md->Html conversion, set to False when only wanting to get proper markdown from Obsidian
  compile_html: True

  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: False

  # Can be overwritten ad-hoc by using "obsidianhtml -i config.yml -v" (the -v option)
  verbose_printout: False

  # This option should be False for Obsidian->Md, but can be True when compile_md == False
  # Setting it to True will cause an error when two files with the same file name are found anywhere in the input folder
  allow_duplicate_filenames_in_root: False

  # Sometimes linked images that should be local (based on the path) cannot be found.
  # Toggle this to False to disable warnings if that happens.
  warn_on_skipped_image: True

  # This will skip emptying output folders, if you want to implement this yourself
  no_clean: False

  # Whether the markdown interpreter assumes relative path when no / at the beginning of a link
  relative_path_md: True

  # Whether external http anchor links should have a target of "_blank"
  external_blank: False  
```

Could you share the actual links of the notes in Obsidian, and their respective actual filepaths in your vault, and in the markdown output folder?

Also it might be useful to know what version you are using. Could you share the output of `pip show obsidianhtml`?
