### ISSUE TITLE
Feature Request: audio/video Intergration

### ISSUE THREAD

**Issue by Krrrrrrk** [obsidian-html/obsidian-html#183]
I utilize small .mp4's in my notes frequently. Any plans to integrate handling that file format? I tried adding it to `image_suffixes = ['jpg', 'jpeg', 'gif', 'png', 'bmp', 'pdf', 'mp4]` but as expected that didn't work, since HTML handles video in a separate `<video>` tag.

**Comment by dwrolvink** [comment]
cool idea. I'm a pretty basic user myself so I miss a lot of these usecases.

The new code in master should implement this. You could do a git pull in the obsidianhtml folder and try it out.

Note: to implement this, these changes have been made to the default_config.yml:
``` yaml
included_file_suffixes: ['jpg', 'jpeg', 'gif', 'png', 'bmp', 'pdf', 'mp4']
video_format_suffixes: ['mp4']
```

**Comment by Krrrrrrk** [comment]
I can't begin to tell you how awesome you are. Can I push my luck and ask for .mp3 and .wav integration as well? :D It utilizes the `<audio>` tag in HTML.

**Comment by dwrolvink** [comment]
haha, might as well, seeing how it's exactly the same idea

happy you like the package, it's very nice to build something and get it to the point that it is good enough for other people to use it :)

**Comment by dwrolvink** [comment]
Alright, that was an easy addition it seems

Update once more in default_config.yml (if you don't have these values set you don't have to do anything btw)
``` yaml
included_file_suffixes: ['jpg', 'jpeg', 'gif', 'png', 'bmp', 'pdf', 'mp4', 'wav', 'mp3']
video_format_suffixes: ['mp4']
audio_format_suffixes: ['wav', 'mp3']
```
