### ISSUE TITLE
[Feature Request] - TOC

### ISSUE THREAD

**Issue by dr-code** [obsidian-html/obsidian-html#212]
Feature Request: Layout like the Material by MKDOCS regarding the TOC/Contents

Just re-linking here: https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors

**Comment by dwrolvink** [comment]
Alright, as I said, this is going to take a while to implement correctly, but if you're curious, here's the current proof-of-concept:

![image](https://user-images.githubusercontent.com/30291690/163048826-63a933a3-3aa5-4f62-8a17-e43524012013.png)

Still have to write some code to open the correct navigation folders and then mark the current page. (And then still the work to make sure it is correctly configurable / that it doesn't break anything else / clean up technical debt).

But nice preview anyways, might change something like this to the default, I have the feeling that most people don't really care that much for the tab system, bit too much of a novelty, this might make a more sensible default layout.

**Comment by dwrolvink** [comment]
The code for this is in https://github.com/dwrolvink/obsidian-html/tree/template-rewrite btw, so if you want to try it out, you could install that branch.

**Comment by dr-code** [comment]
Yes definitely think this would be a much better default layout! Looks good! I'm not exactly sure how to try it out unfortunately.

**Comment by dwrolvink** [comment]
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/dwrolvink/obsidian-html@template-rewrite
```

and when you want to go back to the stable release you'd do:
``` bash
pip uninstall obsidianhtml
pip install obsidianhtml
```

Make sure that 
``` yaml
toggles:
  no_tabs: True
```
is configured.

**Comment by dr-code** [comment]
yup got it to work!

Since the left side is pulling every single markdown file, I grouped together my two major topics in folders and removed the big table I had in entrypoint.md. When I did that, it removed all of the links. So I created a home page for each of the two major topics and put that home page in each of its respective folders. That did the trick!

I'm wondering (similar to the MkDocs/Material format) if a Nav bar would be beneficial here. Ive attached a picture to show you what I mean.

<img width="1374" alt="obsidianhtml_TOC" src="https://user-images.githubusercontent.com/8603561/163183761-a0d058dc-3a99-4d21-a4db-ff75c440a4b2.png">

These are just ideas/suggestions of course.

With the template-rewrite, im not sure if you're having this issue but this is what's happening with mine when I click on any of the folder links: 
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/8603561/163184089-a18a48de-54f0-45ba-9a29-35e869de3f36.png">

Notice the two grey bars on the left side. They don't stay if I click on a different link or it comes up as one grey bar that looks like is crossing the text. 

Thanks

**Comment by dwrolvink** [comment]
Yes good points about the nav bar and the toc
Though it assumes a lot of things, for one that you organize your folders / each note in a certain way. For example, some people might not use an h1 header for the note title, so in that case you would want the first h1 in the toc. I for example use the first h1 for the main topic, and then more h1's for related topics. In any case I don't think it is that intrusive to have it there, right?

It's actually best practice for note taking to keep a very flexible structure, that kind of prohibits making a whole thought out folder structure from the get go. Though here you are not really note taking, but building a documentation, which is also a valid usecase, just a totally different one than what this package was originally designed for.

The biggest issue lies with the nav bar, having too many toplevel folders would make the navbar huge. These are things that are easy to tweak when you have only one set of content, but for every conceivable vault it becomes a lot less easy.

I haven't seen the gray bars, what browser are you using?

**Comment by dr-code** [comment]
Not at all intrusive. I completely understand my use case is different. 

You're right about others and note taking, for me note taking is essentially building a documentation which is different as you mentioned.

hmm I see your point about the navbar, potential customization for the future?

I tried it with google chrome and there are no gray bars there. but they do exist on Safari; so no big deal. 

Thanks

**Comment by dwrolvink** [comment]
current progress:
![image](https://user-images.githubusercontent.com/30291690/163249646-6712d48e-4811-4e95-b2fa-2a2c714c4842.png)

you can try it out by doing:
``` bash
pip uninstall obsidianhtml
pip install git+https://github.com/dwrolvink/obsidian-html@template-rewrite
``` 
once more.

I hope that the scrollbars are gone now because I can't run safari (natively) on linux.
Again, this might introduce new bugs, still working on it, but curious on what you think of this layout so far.

p.s. 
you can set the following metadata on a note to disable the left pane for when it is not relevant:
``` plaintext
---
obs.html:
  disable_dir_nav: true
---

# My note
Hi mom
```

**Comment by dwrolvink** [comment]
p.s. 2

I have made the navbar configurable, like so:
``` yaml
navbar_links:
  - name: Quickstart
    link: Instructions/Quickstart.html
  - name: News
    link: MOCs/News.html
  - name: About
    link: General Information/About ObsidianHtml.html
  - name: Modes
    link: Configurations/Modes.html
  - name: Features
    link: MOCs/Features.html
  - name: Configurations
    link: Configurations/Configuration Options.html

toggles:
  features:
    styling: 
      module: documentation
      accent_color: '#414cfd'
```

So you can add that and edit it for your own usecase.

**Comment by dr-code** [comment]
it works! Looks really good. 
No gray bars either!

I also removed the notes with that metadata that I didn't want visible so that works as well!

**Comment by dwrolvink** [comment]
Nice :) 
I'll post an update here when it will be released in the mainline version.

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/Changelog/v2.0.0.html :confetti_ball:

**Comment by dr-code** [comment]
I'd hate to open this up but once I updated to the new obsidianhtml. 
Im getting this:
<img width="1759" alt="image" src="https://user-images.githubusercontent.com/8603561/164353162-55e650ba-915f-4d96-9ac4-ef41d850e1e9.png">

This is my config.yaml file:
```
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '/Users/rutvik/Documents/4. Career/4.8 Knowledge Bank/PulmCrit' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '/Users/rutvik/Documents/4. Career/4.8 Knowledge Bank/PulmCrit/entrypoint.md'

html_output_folder_path_str: '/Users/rutvik/Documents/1. Personal Development/1.1 Projects/git/dr-code.github.io'
# html_custom_inclusions:
  # - '<link rel="stylesheet" href="/src/custom.css"/>'

site_name: 'Pulmonary Critical Care Notes'
navbar_links:
  - name: Pulmonary
    link: Pulmonary Medicine/Pulmonary Medicine Home.html
  - name: Critical Care
    link: Critical Care Medicine/Critical Care Medicine Home.html

toggles:
  relative_path_html: False
  features:
    graph:
      enabled: True          # Include code to build the graph view per page (default: True)
      template: node_graph
      #coalesce_force: '-700' # How close the nodes will be to eachother.
    create_index_from_dir_structure:
      enabled: True
      exclude_subfolders:
        - ".git"
        - "src"
        - "md"
        - "obs.html"
        - "output"
      exclude_files:
        - "index.html"
        - "favicon.ico"
        - "not_created.html"
        - ".DS_Store"
    # Show backlinks at the bottom of each note
    backlinks:
      enabled: True
    styling:
      layout: no_tabs
      add_toc: True
      toc_pane: True
      flip_panes: False
      max_note_width: 52rem
      accent_color: '#414cfd'
  no_clean: True
```

Not sure where I'm going wrong because it was working with the testing as above.

**Comment by dwrolvink** [comment]
No problem opening issues, that's what they are for.
What is wrong with the output?

If you want the main note to be wider you can set `max_note_width: 100%` or `max_note_width: 200rem`, etc.

**Comment by dwrolvink** [comment]
btw if you want the content view, you should set 

``` yaml
toggles:
  features:
   styling:
      layout: documentation
```
