### ISSUE TITLE
[Feature Request] Allow use of external links in the nav bar menu

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#299]
@dwrolvink How would you go about having some of the nav bar menu options linking to an external site (for example Github / Twitter or any other personal project)?

My use case is to do a personal website (github page) which would have 2 sides (a wiki and a portfolio part), and I would like to make it easy to switch from one to the other.

_Originally posted by @adrien-perello in https://github.com/obsidian-html/obsidian-html/issues/212#issuecomment-1196640079_

**Comment by dwrolvink** [comment]
Hi @adrien-perello 

That is not yet supported in the latest released version. I've added some code to master that aims to implement this.

> For instructions on how to install the master branch code instead of the pip version see here: https://obsidian-html.github.io/Instructions/Install%20a%20different%20version.html

You can add an external link to your navbar by including the `type: external` keyvalue pair, like so: 
``` yaml
navbar_links:
  - name: Home
    link: index.html
  - name: Code
    link: https://github.com/obsidian-html/obsidian-html
    type: external    
```

Here is the relevant code, if it interests you: https://github.com/obsidian-html/obsidian-html/blob/37aee2a787c1435022c88ca04cad752269ee824b/obsidianhtml/__init__.py#L729-L734

Let me know how this works for you!
