### ISSUE TITLE
[Feature Request] Allow for certain lines to be removed based on regex

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#316]
Related to #306 

The zoottelkeeper plugin writes output like this:
``` md
%% Zoottelkeeper: Beginning of the autogenerated index file list  %%
-  [[Buglog/test/File links in dirtree note do not work|File links in dirtree note do not work]]
-  [[Buglog/test/Spaces in front of headers allowed by Obsidian but not by ObsidianHtml|Spaces in front of headers allowed by Obsidian but not by ObsidianHtml]]
%% Zoottelkeeper: End of the autogenerated index file list  %%
```

We want to only keep the links,  so remove everything that starts with `%% Zoottelkeeper:` until we get to `%%$`

@bhickta

**Comment by dwrolvink** [comment]
Add this to your config yaml:

``` yaml
toggles:
  features:
    eraser:
      enabled: True
      verbose: True
      opening_sequence: |-
        (^%% Zoottelkeeper: )
      closing_sequence: |-
        (^.+ +%% *$)
```
That should remove the zoottelkeeper lines and not touch anything else (hopefully).

**Comment by dwrolvink** [comment]
Alright, change of tactics.

I just noticed that the `%%` syntax is just a general comment syntax in Obisidian. I just recreated this functionality. This makes the eraser extension way more general,  so general in fact that configuration is no longer necessary.

Config for the feature has thus been reduced to 
``` yaml
toggles:
  features:
    eraser:
      enabled: True
```

This is the default setting so the whole block can be removed if wished.
Using the config in the post above will result in errors.

This is the current behavior:
```
Obisidian has a comment system: everything between %% is a comment and will not be shown in view mode

    Text
    %%
    comment block
    %%
    Text

    Text %% inline comment %% text

This extension removes these comments. 
%% in codelines/-blocks are ignored.
```

If anyone has a usecase for a more configurable way to remove stuff from notes just post here / create a new feature request for it.
