### ISSUE TITLE
KeyError: 'external-references'

### ISSUE THREAD

**Issue by hgrw** [obsidian-html/obsidian-html#347]
I have a documentation structure like

{REPO}/Documentation Home.md, which has a link

[[Subsystem Home]]

where Subsystem Home is located in subdirectory:

{REPO}/{SUBSYSTEM}/{SUB-SUBSYSTEM}/Subsystem Home.md

{SUB-SUBSYSTEM} is a submodule and it is a fairly rich homepage for sub-subsystem documentation. On generating the config I get error `KeyError: 'external-references'`. Digging around a little:

Printing result (GetObsidianFilePath(link, self.file_tree, self.pb)): `Result:  {'rtr_path_str': 'Documentation Index.md', 'fo': <obsidianhtml.PathFinder.OH_File object at 0x7f4bf0277d60>, 'header': 'External References', 'alias': 'External References'}`

Site generator config:
```
##########################################################################
#                               PATHS                                    #
##########################################################################
# The first folder that contains all obsidian files
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: ''

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Can be absent when toggles/compile_md == False
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: 'Documentation Index.md'

# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_folder_path_str: 'public/md'

# Markdown entrypoint path
# This has to be md_folder_path_str + '/index.md' when toggles/compile_md == True
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
md_entrypoint_path_str: 'public/md/index.md'

# Output path of HTML files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
html_output_folder_path_str: 'public'

# If extended logging is enabled under toggles/extended_logging
# Extra information is written to this folder
log_output_folder_path_str: 'public/log'

##########################################################################
#                              OPERATIONS                                #
##########################################################################
# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_subfolders:
  - ".obsidian"
  - ".trash"
  - ".DS_Store"
  - ".git"
  - ".gitignore"
  - ".gitmodules"
  - ".gitlab-ci.yml"

included_file_suffixes: [ 'jpg', 'jpeg', 'gif', 'png', 'bmp', 'pdf', 'mp4','webm', 'wav', 'mp3', 'svg' ]
video_format_suffixes: [ 'mp4', 'webm' ]
audio_format_suffixes: [ 'wav', 'mp3' ]

# Used to strip the http url hostpart of a link to get a relative link
# e.g. for value "https://git.com/user/repo/-/wikis/mywiki/" then:
#   "https://git.com/user/repo/-/wikis/mywiki/folder/markdown.md" --> /folder/markdown.md
md_source_host_url: ''

##########################################################################
#                             HTML OUTPUT                                #
##########################################################################

# Will be inputted into the Html template as page title
# Not used anywhere else atm.
site_name: 'Home'

# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: '/rf-systems/documentation'

navbar_links: [ ]

##########################################################################
#                    OPTIONAL BEHAVIOR / FEATURES                        #
##########################################################################
toggles:
  # Can be overwritten ad-hoc by using "obsidianhtml -i config.yml -v" (the -v option)
  verbose_printout: False

  # Write extra information to log_output_folder_path_str
  extended_logging: False

  # This option should be False for Obsidian->Md, but can be True when compile_md == False
  # Setting it to True will cause an error when two files with the same file name are found anywhere in the input folder
  allow_duplicate_filenames_in_root: False

  # If this is false only the entrypoint and all its links (recursively) are processed
  # if true all the notes will be processed
  process_all: False


  features:
    styling:
      layout: documentation               # documentation, tabs, minimal
      max_note_width: 120rem              # not supported for layout: tabs
      add_toc: True                       # add "[TOC]" (Table of Contents) when missing
      toc_pane: True                      # removes table of contents from the note and puts it in the right pane (not supported for layout:tabs)
      flip_panes: False                   # switch right and left pane around. (does nothing unless in documentation layout.)
      add_dir_list: True                  # show directory contents in one of the panes (only documentation layout)
      accent_color: '65, 76, 253'
      loading_bg_color: '255, 255, 255'

    theme_picker:
      enabled: True
      styling:
        show_icon: True

    code_highlight:
      enabled: True
    mermaid_diagrams:
      enabled: True
    callouts:
      enabled: True
    math_latex:
      enabled: True
    backlinks: # Show backlinks at the bottom of each note
      enabled: True

    search:
      enabled: True
      styling:
        show_icon: True

    tags_page:
      enabled: True
      styling:
        show_icon: True
        show_in_note_footer: True

    dataview:
      enabled: False
      folder: 'obs.html/export' # relative to the vault being processed. this folder should always be in the vault

    # Include code to build the graph view per page 
    graph:
      enabled: True           # Include code to build the graph view per page (default: True)
      templates:
        - id: 3d
          name: 3d
          path: builtin<3d>
        - id: 2d
          name: 2d
          path: builtin<2d>
      styling:
        show_icon: True
      coalesce_force: '-30'

    # Create an index.md with links to notes that have one of the given tags.
    # This index.md will serve as the entrypoint.
    # !! Enabling this feature will overwrite obsidian_entrypoint_path_str and md_entrypoint_path_str
    create_index_from_tags:
      enabled: False
      add_links_in_graph_tree: True
      tags: [ ]
      sort:
        method: 'none'          # <key_value, creation_time, modified_time, none>    ! created_time not available on Linux!
        key_path: ''            # empty for top level, use ':' to go down multiple levels
        value_prefix: ''        # in case of multiple values under key_path, match on this prefix, and then remove prefix
        reverse: false          # false/true reverses output
        none_on_bottom: true    # will put notes at the bottom that do not have the sort key, otherwise at the top
      exclude_paths: # don't included these paths in the dir list
        - ".gitignore"

    create_index_from_dir_structure:
      enabled: True
      rel_output_path: 'obs.html/dir_index.html'
      styling:
        show_icon: True
      exclude_subfolders:
        - ".git"
        - "__src"
        - "md"
        - "obs.html"
      exclude_files:
        - "favicon.ico"
        - "not_created.html"
```
