### ISSUE TITLE
Images not being included in html output

### ISSUE THREAD

**Issue by wealthychef1** [obsidian-html/obsidian-html#366]
Hello, this is the exact same setup as in issue https://github.com/obsidian-html/obsidian-html/issues/358

The code appears to compile correctly but images are not included. 
```bash
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml -i config.yaml 
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/WatchOS/Putting Apple Watch into Sleep mode for respiratory data.md)
> COMPILING HTML FROM MARKDOWN CODE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/output/md/index.md)
index.md
	> COMPILING INDEX FROM DIR STRUCTURE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/output/html/obs.html/dir_index.html)
	< COMPILING INDEX FROM DIR STRUCTURE: Done
	> SECOND PASS HTML
	< SECOND PASS HTML: Done
< COMPILING HTML FROM MARKDOWN CODE: Done
rcook@MacBook-Pro-2021 (Obsidian development ): 
```
Input config file: 
```yaml
##########################################################################
#                               PATHS                                    #
##########################################################################
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/WatchOS/Putting Apple Watch into Sleep mode for respiratory data.md'

# Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect the vault data. 
# Should be fine to turn off if copying the vault takes too long / disk space is too limited.
# The tempdir is automatically removed on exit of the program.
copy_vault_to_tempdir: False

toggles:
  debug_filetree_keys: False
```
Here is the original markdown:
```markdown
---
Aliases: [   ]
tags: 
created: 2022-08-31
# Note refactored from [Apple Watch is not collecting respiratory data for AutoSleep app](Apple%20Watch%20is%20not%20collecting%20respiratory%20data%20for%20AutoSleep%20app.md) 
---
#  Putting Apple Watch into Sleep mode for respiratory data
 - Apple appears to require that the watch be put into a special mode called "Sleep" which is of course different from "sleep" as applied to MacOS or iOS. 
1. First set up a sleep schedule in Health, which is just a declarative process; Apple does nothing much with it. 
	1. I suppose being conscious is perhaps the heart of measurement, so this does have a benefit for self discipline, whatever benefit Apple intends.  
2. On the watch, swipe up, select the moon icon
	1. ![200](4F9FC2B4-E310-40AF-AFA6-B9DDA9A3C10B_1_201_a.jpeg)
3. we see that now it presents a choice between "Sleep" and "Do Not Disturb." Choose "Sleep."
	1. ![200](B89FBF45-E83F-444A-B74F-371EB0DB8730.png)
4. Now the Moon has changed to a bed.  
	1. Meaning?  You are sort of "likely to be sleeping" as far as Apple is concerned.  Weird gray area here. 
		1.  ![200](E718F31D-4691-41B3-8D23-D48696EC3F28.png)
5.  The watch now is going to collect respiratory data (all the time? unknown)
6. Autosleep and Health now show the respiratory data. 
7. Support told me, before we were cut off due to poor reception in TJ, that sleep schedules and the Sleep function on the watch functioned as a hint from me to the OS. 
	1. Actually, it's more than this, see [#Collection of data](#Collection%20of%20data)
	2. I imagine perhaps taking respiratory measurements uses more power, but later call shed doubt on this idea.  
8. Feels a bit like terrible design by Apple.  Needs improvement.  They keep getting the basic things wrong, LOL

### Collection of data
- Respiratory rate is calculated from blood oxygen levels
- In the watch app, the Blood Oxygen setting allows control of when it's collected
	- During sleep focus and/or during Theatre Mode
	- ![150](09451C84-DDD3-4A2C-868B-D84C54B26778_1_105_c.jpeg)
- In addition computation and availability of respiratory rate requires:
	- I'm not physically in motion.  
	- Phone has to be inactive.  
	- Phone needs to be charging as well.  
	- Watch has to be in Sleep mode
		- This happens automatically at the start of the Sleep Schedule from the iOS Health app.  
		- This mode is only available if there is an existing sleep schedule. 
	- The devices will then use motion and other data to drive further analyses

### Next update should improve things
- The next update (iOS 16) is better in terms of measurements  

### The utility of setting an extended sleep schedule  
- I considered setting my sleep schedule to be all day, but I think that's not necessary.  
- Sleep mode on the watch is available outside the schedule, just needs to be manually enabled.  
- Since my schedule is in fact variable, I have to just remember to set Sleep mode when I lay down, not a big deal.  
```

Here is the result: 
[output.zip](https://github.com/obsidian-html/obsidian-html/files/9483177/output.zip)

Note the images are not included.  Perhaps I'm using this wrong or making another obvious mistake.  :-)

**Comment by dwrolvink** [comment]
What is the location of, for example, 09451C84-DDD3-4A2C-868B-D84C54B26778_1_105_c.jpeg in your vault?

**Comment by dwrolvink** [comment]
Ah I've found the issue.
Try to open a terminal,  and going into the html output folder. For me this was `~/Downloads/output/output/html`. (The folder with the index.html`. Then run `python -m http.server`. Then open this link in your browser: http://localhost:8000

That should work, works for me at least:
![image](https://user-images.githubusercontent.com/30291690/188284145-7aaa2dad-3392-4f54-8840-25a8839b9ded.png)

**Comment by dwrolvink** [comment]
You've missed this step: https://obsidian-html.github.io/Instructions/Quickstart.html#!test-website

There is [a setting that can enable you to view your website directly from your filesystem](https://obsidian-html.github.io/Configurations/Relative_path_html.html) (so without starting a webserver every time), but that way you can't have graph view, search, and currently the directory navigation and the website navigation won't work with this setting. 

What does work is an output like this: https://obsidian-html.github.io/Configurations/Relative_path_html.html (minus the graph view).

I'm going to create an issue to upgrade this functionality and test the other newer features with it, but viewing the html output via a webserver is highly recommended.

**Comment by dwrolvink** [comment]
Okay I fixed the links for the directory and website navigations, clicking around, all the links seem to work now with that setting. Make sure to disable the graph view and the search feature if you opt to use `relative_path_html`.

**Comment by wealthychef1** [comment]
> You've missed this step: https://obsidian-html.github.io/Instructions/Quickstart.html#!test-website
> 
> There is [a setting that can enable you to view your website directly from your filesystem](https://obsidian-html.github.io/Configurations/Relative_path_html.html) (so without starting a webserver every time), but that way you can't have graph view, search, and currently the directory navigation and the website navigation won't work with this setting.
> 
> What does work is an output like this: https://obsidian-html.github.io/Configurations/Relative_path_html.html (minus the graph view).
> 
> I'm going to create an issue to upgrade this functionality and test the other newer features with it, but viewing the html output via a webserver is highly recommended.

Thank you for pointing this out.

What I'm actually trying to do is display this page on my apache2 web server at an arbitrary location under $DOCUMENT_ROOT

To do so, I copied the html directory to my webserver in a subdirectory named "test" like this:
```bash
scp -r output/html webserver.com:${DOCUMENT_ROOT}/test
```

You can see the result here: https://wealthychef.net/test/index.html

What am I doing wrong?  Thank you.  I am drooling over the promise of graphs and search, but I somehow am managing to fail still to just get this basic case working.   As you say, I have a knack for finding problems because I kind of do things my own way.  I learn a lot this way but bump into things too.  
Once I master a single file, we can start graphing relationships, my mind boggles at doing two files at the same time!  And to be able to choose a larger "subvault" or piece of my vault graph if you will, it would be amazing.

**Comment by wealthychef1** [comment]
> What is the location of, for example, 09451C84-DDD3-4A2C-868B-D84C54B26778_1_105_c.jpeg in your vault?

Here is the location

```bash
rcook@MacBook-Pro-2021 (wealthyvault (master)): find ./ -name 09451C84-DDD3-4A2C-868B-D84C54B26778_1_105_c.jpeg
.//assets/09451C84-DDD3-4A2C-868B-D84C54B26778_1_105_c.jpeg
```

**Comment by wealthychef1** [comment]
> Okay I fixed the links for the directory and website navigations, clicking around, all the links seem to work now with that setting. Make sure to disable the graph view and the search feature if you opt to use `relative_path_html`.

Can you say more about this setting?  I'm sorry I need to do more research about this functionality, I'm learning as I go right now.  Is this an RTFM moment?  :-) 

More importantly, how do emojis work on this forum?

**Comment by wealthychef1** [comment]
Running  a local python webserver with output/html as document root works well for me as you instructed.  However as i pointed out [earlier](https://github.com/obsidian-html/obsidian-html/issues/366#issuecomment-1236272760) the same directory does not work properly on my actual apache server, probably having connection to the use of absolute pathnames in the html. 

> Ah I've found the issue. Try to open a terminal, and going into the html output folder. For me this was `~/Downloads/output/output/html`. (The folder with the index.html`. Then run `python -m http.server`. Then open this link in your browser: http://localhost:8000
> 
> That should work, works for me at least: ![image](https://user-images.githubusercontent.com/30291690/188284145-7aaa2dad-3392-4f54-8840-25a8839b9ded.png)

**Comment by wealthychef1** [comment]
> What does work is an output like this: https://obsidian-html.github.io/Configurations/Relative_path_html.html (minus the graph view).
> Okay I fixed the links for the directory and website navigations, clicking around, all the links seem to work now with that setting. Make sure to disable the graph view and the search feature if you opt to use `relative_path_html`.


When I tried to use this setting:  

```yaml
toggles:
  debug_filetree_keys: False
  relative_path_html: True
  ```

I got this: 
```bash
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml --test
test 3.2.0 d
rcook@MacBook-Pro-2021 (Obsidian development ): obsidianhtml -i config.yaml 
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/WatchOS/Putting Apple Watch into Sleep mode for respiratory data.md)
> COMPILING HTML FROM MARKDOWN CODE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/output/md/index.md)
index.md
	> COMPILING INDEX FROM DIR STRUCTURE (/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/output/html/obs.html/dir_index.html)
	< COMPILING INDEX FROM DIR STRUCTURE: Done
	> SECOND PASS HTML
	< SECOND PASS HTML: Done
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/obsidianhtml", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidianhtml/__init__.py", line 997, in main
    html_url_prefix = pb.sc(path='html_url_prefix', value=get_rel_html_url_prefix(rel_dst_path_as_posix))
NameError: name 'rel_dst_path_as_posix' is not defined. Did you mean: 'tag_dst_path_posix'?
rcook@MacBook-Pro-2021 (Obsidian development ): 
```

**Comment by dwrolvink** [comment]
> You can see the result here: https://wealthychef.net/test/index.html What am I doing wrong?

Good news! There is a setting for this! :joy: 

**Some backstory** 
When obsidianhtml creates the links, it creates absolute links (relative to the root of a website domain), for example `/index.html`. Such a link will point to `https://wealthychef.net/index.html`. Notice that your `test/` is gone. So with your current settings, none of the links will work, this also shows in that the stylesheet cannot be loaded, causing a very ugly website.
 
When you use `relative_path_html: True`, then obsidianhtml will create links relative to whatever page you are currently on. So when visiting `https://wealthychef.net/test/index.html` the link to index.html will be `./index.html` and when visiting `https://wealthychef.net/assets/list.html` the link to index.html will be `../index.html`.

Now, using absolute paths is the most stable, so instead we can also use the first option while just always prefixing `/test` to any link. This would also solve your problem. This can be done like so: https://obsidian-html.github.io/Configurations/Configuration%20Options.html#!html-url-prefix

**Instructions**
 So in short,  add this to your yaml:
``` yaml
# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: '/test'
```

Make sure to remove the relative_html setting.
That should make your config yaml look like this:

**Resultant yaml**
``` yaml
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
obsidian_folder_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault' 

# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
obsidian_entrypoint_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Knowledge/Computers/WatchOS/Putting Apple Watch into Sleep mode for respiratory data.md'

# Use when deploying to https://mydomain.com/html_prefix/ instead of https://mydomain.com/
# use '/html_prefix' (prepend slash, no slash at the end)
html_url_prefix: '/test'

# Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect the vault data. 
# Should be fine to turn off if copying the vault takes too long / disk space is too limited.
# The tempdir is automatically removed on exit of the program.
copy_vault_to_tempdir: False

toggles:
  debug_filetree_keys: False
```

**Misc**
I should really add a deployment section to the quickstart page, because this one comes up pretty often and it is not easily found in the documentation.
edit:
https://obsidian-html.github.io/Instructions/Quickstart.html#!deployment-configuration
https://obsidian-html.github.io/Instructions/Usage.html#!deployment-configuration

Regarding the bug you got, I had fixed that yesterday already before I posted, but I forgot to tell you to update the code again.
Shouldn't matter anymore now though.
