### ISSUE TITLE
idea: it would be a good feature to have a dynamic entrypoint based on a tag

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#44]
It would be a nice feature to be able to have a entrypoint index html based on a tag.

Such as #my-entrypoint-links

Could build an index.md based on those tags and convert from that entrypoint.

**Comment by dwrolvink** [comment]
Hmm yes, that could work, provided `process_all: True`. Because the tags are currently only discovered during the processing of a file. 

To change that, (so to have it also work for `process_all: False`) we'd first need to build a tagtree, then find all the notes with the configured tag, build an index.md, set that as the entrypoint, and then run as normal.

Sounds like this could be something that is run entirely separately from the current flow, like a function that checks if such a tag exists, then runs the normal flow with an extra argument to denote it should only build the tagtree. Then builds the index and then updates the config vars, after which the normal flow will kick off like nothing happened.

This is kind of the reason I opted initially to just create a note with links to everything that I wanted to include, and just iterate over that note, way simpler. But I guess the introduction of `process_all` opened the door to this feature. I can imagine how it would be comfy to just add a tag to a note that you have currently opened and have it be included in the homepage.

Though I expect the feature request of ordering the resulting index.md on alphabetical order / date tags / etc :face_with_spiral_eyes:  Complexity begs more complexity

**Comment by dwrolvink** [comment]
working on this

**Comment by dwrolvink** [comment]
@jcolson see the commit __in my fork__, if you want you can try if this works for you.

It needs these config settings to work:
``` yaml
toggles:
  process_all: True

  features:
    # Create an index.md with links to notes that have one of the given tags.
    # This index.md will serve as the entrypoint
    # !! Enabling this feature will overwrite obsidian_entrypoint_path_str and md_entrypoint_path_str
    # !  Will only work for process_all: True at the moment.
    create_index_from_tags:
      enabled: True
      tags:
        - tag1
        - tag2     
```

Optional:
``` yaml
toggles:
  features:
    create_index_from_tags:
      add_links_in_graph_tree: True # The index.md will be created, and thus will be without links, this setting will create links to the notes that are matched.    
```

I want this to be better tested before committing to master. 
I'll continue next weekend probably, so you might find it useful in the mean time.
