### ISSUE TITLE
Images with size attribute are not being handled in my vault

### ISSUE THREAD

**Issue by wealthychef1** [obsidian-html/obsidian-html#454]
Hello, 
When I parse one of my documents, some of the images are not copied to my webpage.  I believe it's obsidianhtml's fault. 
```bash
rcook@MacBook-Pro-2021 (vaultToWebsite (master)): obsidianhtml version
3.2.3 B
```
Example of an image that does not get copied:
```markdown
- ![[2022-10-26.21.45.35.CleanShot.Finder.png|500]]
```
If I remove the size attribute, so it is simply
```markdown
- ![[2022-10-26.21.45.35.CleanShot.Finder.png]]
```
Then the image is properly handled, i.e., I see it on my [webpage](https://blog.wealthychef.net/vault-blog/html/Knowledge/Computers/iOS/ExpressVPN%20blocks%20iPad%20connecting%20to%20the%20Finder.html).  
Is this a regression?  I see [in the documentation](https://obsidian-html.github.io/Demonstrations/Parsing%20Images,%20videos,%20and%20audio.html#obsidian-type-image-links) that it should work with the size attr.  
I get no errors during parsing. I don't see anything in the verbose output that shows me anything suspicious.  The file in question does get copied into the md directory.  
```
Copying file over (mode=ntm) from /private/var/folders/jx/xb_hb6h50f95qzrs00rqdkv80000gn/T/tmpecnm_tle/assets/2022-10-26.21.45.35.CleanShot.Finder.png to /Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/vaultToWebsite/vault-blog/md/assets/2022-10-26.21.45.35.CleanShot.Finder.png
```
Not sure how to debug further. 

Here is my config file:
```yaml

##########################################################################
#                               PATHS                                    #
##########################################################################

# --------------------------------------------------------------
# DEFINITIONS
# obsidian_folder_path_str 
# The first folder that contains all obsidian files
# Use full path or relative path, but don't use ~/
# 
# obsidian_entrypoint_path_str 
# The note that will be used as the index.html 
# should be in obsidian_folder_path_str
# Use full path or relative path, but don't use ~/
#
# html_output_folder_path_str
# Output path of HTML files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
#
# md_folder_path_str
# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
#
# log_output_folder_path_str
# If extended logging is enabled under toggles/extended_logging
# Extra information is written to this folder

# Universal: 
obsidian_entrypoint_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault/Projects/Blog Home Page.md'
html_output_folder_path_str: 'vault-blog/html'
md_entrypoint_path_str: 'vault-blog/md/index.md'
md_folder_path_str:  'vault-blog/md'
log_output_folder_path_str: 'vault-blog/log'

# Title for website
site_name: 'Obsidian Blog'

# Deployed at /vault-blog/html/index.html
html_url_prefix: '/vault-blog/html'

## MacOS:
obsidian_folder_path_str: '/Volumes/2_TB_SSD_external/Projects_2TB/computers-and-geekery/projects and languages/Obsidian development/wealthyvault' 

# --------------------------------------------------------------

# Safety feature: make a copy of the provided vault, and operate on that, so that bugs are less likely to affect the vault data. 
# Should be fine to turn off if copying the vault takes too long / disk space is too limited.
# The tempdir is automatically removed on exit of the program.
copy_vault_to_tempdir: True
copy_vault_to_tempdir_method: rsync

# Exclude subfolders
# These are relative to obsidian_folder_path_str
# To exclude a folder two levels deep, use level1/level2
exclude_subfolders:
  - ".obsidian"
  - ".trash"
  - ".DS_Store"
  - ".git"
  - "Personal Journal"
  
  
toggles:
  debug_filetree_keys: False
  relative_path_html: False
  
 ```
