### ISSUE TITLE
graph config error 

### ISSUE THREAD

**Issue by welpdx** [obsidian-html/obsidian-html#482]
When using the default config for graph view as indicated [here](https://obsidian-html.github.io/Configurations/Features/Graph%20view.html#!configure-graph-view), I get this error:
![img](https://i.imgur.com/YKUqgj1.png)

If I remove the other config and just leave it as:
```yaml
    graph:
      enabled: True    
```

It works fine. 

I'm not a ~~rapper~~ programmer, but it looks like the '2d' and '3d' options are not [here](https://github.com/obsidian-html/obsidian-html/blob/75202f14e79e0628c6200a7f88bb6dffdf07e029/obsidianhtml/ConfigManager.py#L200) eh? I am assumming because it is enabled by default?

Thanks for your clarification.

(btw, tysm for your repo).

**Comment by dwrolvink** [comment]
Ah shucks, I forgot to update that documentation page. 

If you look at the line _Read more: [Writing a custom graph view template](https://obsidian-html.github.io/Configurations/Styling/Writing%20a%20custom%20graph%20view%20template.html)._ And follow that link it does show the correct default config, which is:

``` yaml
    graph:
      enabled: True           # Include code to build the graph view per page (default: True)
      templates:
        - id: 2d
          name: 2d
          path: builtin<2d>
        - id: 3d
          name: 3d
          path: builtin<3d>
      styling:
        show_icon: True
```

Will update this page soon.

Btw, you can check out the current default  config for your version by running: `obsidianhtml export default-config`. 

The most recent version is located here: https://github.com/obsidian-html/obsidian-html/blob/master/obsidianhtml/src/defaults_config.yml#L249

Config checking is done in two steps:
- For each key in the yaml file, there is a check if the key exists in the default_config yaml
- If the key exists, in both files, the types are compared, and are required to be the same. So you can't configure a key to be a string if the value in the default config is a list, for example.

I think this should resolve your question, let me know if you have any other issues regarding the config!
