### ISSUE TITLE
Allow create_index_from_tags to be set as the content for one of the side panes.

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#500]
As discussed here: #489 , `create_index_from_dir_structure` puts stuff in either the left or right side pane when enabled. We want to add this functionality also to the `create_index_from_tags` feature.

To apply this:
- Set the default output path of `create_index_from_tags` to `/obs.html/tag_index.html`
- Add a sidepane feature to manage the increasing supply of side pane content, something like:
``` yaml
toggles:
  features:
    side_pane:             # only valid for documentation layout
      left_pane:
        enabled: True
        contents: tag_tree # <toc, tag_tree, dir_tree> relevant features should be enabled and configured see docs
      right_pane:
        enabled: True
        contents: toc      # <toc, tag_tree, dir_tree> relevant features should be enabled and configured see docs
```

**Comment by dwrolvink** [comment]
![image](https://user-images.githubusercontent.com/30291690/209024701-54285cf4-318b-43d7-a683-9111c62a20d5.png)

Some progress to share.

For the config that was used: https://github.com/obsidian-html/example_vault/blob/500_1/cat_blog.yml
Pretty self-explanatory

This vault was targeted: https://github.com/obsidian-html/example_vault/tree/500_1/vault

Will do some more bugtesting / doc writing somewhere this week.

**Comment by dwrolvink** [comment]
https://obsidian-html.github.io/Configurations/Features/Side%20panes.html

Alright go have a look.  Feedback very appreciated.
I've also added the html_page content source, which allows you to get the html of any note and put it in a side pane.
 
Made the most sense for me to add, because it gives users near complete freedom in what they want to add to the side pane (though at the cost of having to edit the note themselves).

**Comment by erikwestra** [comment]
Thanks, Dorus -- this is a great first cut, and shows you a list of tags and their associated pages as promised.

I did notice a few things, though:

1. It doesn't work for nested tags.  Unlike the `obs.html/tags/index.html` page, nested tags are ignored and the pages are simply listed using the top-level tag.  That means if I have one page with the tag `topic/cycling` and another page with the tag `topic/cats`, both pages would appear in the sidebar under the tag `topic` -- the sub-tags are ignored.

2. Unlike the directory tree, you can't open and collapse the tags.  It'd be great if you could list the tags (like you list folders in the directory tree) and then click on them to open them.  At the moment, if you have more than a few pages with tags on them, the sidebar page would get so long that you'd be scrolling up and down through a list of *all* your tagged pages, which would quickly become unmanageable.  It'd be much better if you showed the list of tags and let users click on them to view the matching pages, just like you do in the directory view to drill down into folders.

(these are both enhancements to this core feature, though -- so I understand if you'd like to tackle these as separate things down the track).

3. I think you've changed the template format, and it's not being used consistently.  If I navigate to the `obs.html/tags/index.html` page, it looks like this:

<img width="871" alt="Screen Shot 2022-12-27 at 8 36 14 AM" src="https://user-images.githubusercontent.com/515597/209578846-5b2f702d-efc7-4ac2-adb3-067c377205d9.png">

I suspect that `{left_pane}` and `{right_pane}` should be replaced with the site's sidebars -- is that correct?

Anyway, thanks for taking the effort to implement this...it's certainly getting there!

 - Erik.

**Comment by erikwestra** [comment]
> I've also added the html_page content source, which allows you to get the html of any note and put it in a side pane.

This looks like an awesome feature, and I can see how useful it can be, though I haven't had any luck getting it to work.

I created a top-level note called `Sidebar.md` that contains some dummy content, and then added the following to my config file:

```
  features:
    side_pane:
        left_pane:
          enabled: True
          contents: html_page
          content_args:
            rel_path: 'Sidebar.html'
            div_selector: '.content'
```

It successfully finds my `Sidebar.html` file, but obsidian-html fails with:

```
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/obsidianhtml/features/SidePane.py", line 72, in get_html_page_content
    for s in div.find('div', attrs={div_attr_type:div_selector}):
TypeError: 'NoneType' object is not iterable
```

It looks like it's not finding the `<div class="content">` tag in the file, even though it's definitely there:

```
<div class="content"><p>This is the sidebar.</p></div>
```

Any ideas why this might be failing?

**Comment by dwrolvink** [comment]
Yes, this is not the part where it gets the content, but the part where it strips divs from the fetched content. 
The default value says to strip the `<div class"toc">...</div>` code, but if you don't have that div it (apparently) gives an error.

So good feedback, should be an easy fix. In the mean time changing your settings to:
``` yaml
  features:
    side_pane:
        left_pane:
          enabled: True
          contents: html_page
          content_args:
            rel_path: 'Sidebar.html'
            div_selector: '.content'
            strip_sub_divs: []
```

Should fix this.

Also very nice feedback on the general feature, I agree with them all, so that will be added at some point.
That just belongs to this issue to get the feature up and workable; we can create new issues for afterthoughts / nice to have stuff.

**Comment by dwrolvink** [comment]
Been awhile, I forget what I already fixed and what not.

> TypeError: 'NoneType' object is not iterable

Fixed just now


> It doesn't work for nested tags. 

This seems to be working fine for me


>  If I navigate to the obs.html/tags/index.html page, it looks like this (picture with placeholders showing)

This should be fixed now


> Unlike the directory tree, you can't open and collapse the tags. 

Changed it so that now it just gets the code from the dedicated tags page.
Has folding tags now, and will be all closed for every page.


I think that should be everything.

I've also added `strip_tags` as a setting, so that you can keep certain tags from ending up in the side pane, e.g. for my site:
``` yaml
toggles:
  features:
    side_pane: 
      left_pane:
        enabled: True
        contents: tag_tree 
        content_args:
          strip_tags:
            - 'babayaga'
            - 'bla'
            - 'randomothertag'
```

(Those tags I use for examples/testing scripts, so should not end up in the tag page).
