### ISSUE TITLE
Possible bugs with tags in the note footer

### ISSUE THREAD

**Issue by erikwestra** [obsidian-html/obsidian-html#512]
I've just come across a couple of weird behaviours that I suspect may be bugs...I'm trying to setup a personal website using obsidian-html, with a directory tree on the left and a tag tree on the right.  So far it's working well, but I'm having trouble with the list of tags shown on the footer of each page.

For starters, here's my overall `config.yaml` file -- I've included the complete file in case there's anything weird I'm doing that could be causing the problem:

```
# The note shown when the site is first displayed.

obsidian_entrypoint_path_str: 'erik.westra.nz/Welcome.md'

# The name of my site.

site_name: "erik.westra.nz"

# My custom HTML template.

html_template_path_str: "template.html"

# Optional behaviour:

toggles:
  process_all: True

  features:
    side_pane:
      left_pane:
        enabled: True
        contents: dir_tree
      right_pane:
        enabled: True
        contents: tag_tree

    create_index_from_tags:
      enabled: True
      tags: [bikepacking]

    create_index_from_dir_structure:
      enabled: True
      homepage_label: "Welcome"
      styling:
        show_icon: True
      exclude_subfolders:
        - "assets"
        - "obs.html"

    styling:
      add_toc: False
      toc_pane: False
      flip_panes: False
      add_dir_list: True

    folder_notes:
      enabled: True
      placement: 'inside folder'
      naming: 'folder name'

    theme_picker:
      enabled: False
    backlinks:
      enabled: False
    search:
      enabled: False
    tags_page:
      enabled: False
    eraser:
      enabled: False
    graph:
      enabled: False
    embedded_note_titles:
      enabled: False
    callouts:
      enabled: True
```

(by the way, if I didn't include `obs.html` in the `exclude_subfolders` list, it would appear in my left sidebar for some reason).

Now, I created a test note with the following contents:

```
# Going for a Ride

#### 31 December 2022

This is a test post about biking.

#bikepacking 
```

Using the above `config.yaml` file, this page gets rendered like this:

<img width="597" alt="Screen Shot 2022-12-31 at 6 18 50 PM" src="https://user-images.githubusercontent.com/515597/210125923-3dbb3d1f-f08c-4a8a-a65f-68dc86a21ebf.png">

As you can see, the inline tag is still displayed, as well as the "Tags" list at the bottom.  Is this a bug, or just a quirk of the way inline tags work?

I then decided to try removing the tags view entirely, so I added the following to the bottom of my `config.yaml` file:

```
    tags_page:
      enabled: False
      styling:
        show_icon: False
        show_in_note_footer: False
```

This resulted in my note being rendered like this:

<img width="597" alt="Screen Shot 2022-12-31 at 6 18 26 PM" src="https://user-images.githubusercontent.com/515597/210125970-e43a576d-30cf-4ea8-94ec-1557e713bd4e.png">

The main part of the generated HTML page looks like this:

```
    <div class="content">
        <h1 id="going-for-a-ride">
            Going for a Ride
        </h1>
        <h4 id="31-december-2022">
            31 December 2022
        </h4>
        <p>
            This is a test post about biking.
        </p>
        <p>
            <code>
                {_obsidian_pattern_tag_bikepacking}
            </code>
        </p>
    </div>
```

As you can see, that `{_obsidian_pattern_tag_bikepacking}` value is rendered using a `<code>` tag, and there doesn't seem to be any way of hiding it using CSS styles.

Is this a bug?  I would have thought that hiding the tag footer will simply remove the "Tags" section at the bottom, not add that weird code to the page.

Thanks!

**Comment by dwrolvink** [comment]
> (by the way, if I didn't include obs.html in the exclude_subfolders list, it would appear in my left sidebar for some reason).

This is correct, that is why the default value is:
``` yaml
    create_index_from_dir_structure:
      enabled: True
      verbose: False
      rel_output_path: 'obs.html/dir_index.html'
      styling: 
        show_icon: True
      exclude_subfolders:
        - ".git"
        - "__src"
        - "md"
        - "obs.html"  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
      exclude_files:
        - ".gitignore"
        - "favicon.ico"
        - "not_created.html"
      homepage_label: "index"
``` 

I like to reuse stuff :)

> Is this a bug? I would have thought that hiding the tag footer will simply remove the "Tags" section at the bottom, not add that weird code to the page.

Yes it's a bug.
The `enabled` does nothing anymore because so many things are dependent on the tags system now that it just always processes. I have run into this issue before with other "features" that morphed into becoming more like a core part. I solved that with "capabilities" which are turned on if there is any one dependent enabled, instead of having just one toggle and providing errors when dependent features are enabled while the required feature is not. This I still have to write for the tag-processing though.

The code of replacing the placeholders and filling in the footer were combined some time back, but the logic was not adjusted. I fixed that for now. Now it just always runs the replacment code. I looked through it and if there is nothing to do it will just not do anything.

I've tested it out on the example vault with every permutation of the `tags_page` settings and it gives me what I'd expect (except for there still being a tags page when tags_page/enabled: False).

I think this will solve your issue.

It's clear that the whole tag control code is a bit of a fixer-upper, but I can't be bothered too much at the moment. When it becomes pressing I'll rewrite the code and make the capabilities integration for it, but until then just know that tags_page/enabled is moot!
