### ISSUE TITLE
Make create_index_from_dir_structure more performant

### ISSUE THREAD

**Issue by dwrolvink** [obsidian-html/obsidian-html#566]
Currently, the feature that builds the directory navigation list (by default the output of the left pane), recreates the navigation list from scratch for each page.

For very large vaults, this becomes an enormous bottle neck. For one such vault, having the default settings result in a compile time of around 13 minutes. When turning off the dir_tree in the left pane, in this manner:
``` yaml
toggles:
  features:
    side_pane:
      left_pane:
        contents: ''
```
The compile time falls back to 1 minute and 17 seconds.

related to #560

We should make a half-fabricate, a dir_tree list that can be easily customized for each page.
