### ISSUE TITLE
Option to slugify filenames and internal links

### ISSUE THREAD

**Issue by sevmonster** [obsidian-html/obsidian-html#574]
While it would be trivial to slugify the filename manually and have Obsidian update references, it would be nice to have an option to allow the generator to automatically slugify for us. That way we can keep nice filenames in the Obsidian file browse UI and web-safe URIs when published through `obsidianhtml`.

**Comment by dwrolvink** [comment]
Great idea, will be picking this up soon!

**Comment by dwrolvink** [comment]
I've got a first version working. It doesn't work together out-of-the-box with the RSS feature yet, I saw.
There are potentially quite many other bugs, but the general process of compiling the output, navigating the site all works fine for me already.

# Enable
Add this key to your config
``` yaml
toggles:
  slugify_html_links: True
```

# Known issues
- The `navbar_links` value will have to be changed when slugifying links
- RSS config will need to be reconfigured when slugifying links
-  Potentially more of these cases, having an automatic conversion of the config would be nice to add.

**Comment by sevmonster** [comment]
I am not sure what parts of the `navbar_links` or RSS config need to be changed, unless you mean include/exclude values there will use the new slugified values. I don't include/exclude anything more strict than the default set so if that's the case I don't think it affects me.

I also see no issues when enabling it. Links look so much better now. I also see no problem with RSS.

**Comment by dwrolvink** [comment]
The problem indeed arises when configuring links with spaces, take for example the documentation config:
``` yaml
# keys omitted for brevity
toggles:
  features:
    rss:
      items:
        selector: 
          include_subfolders: ['Log', 'Changelog']
```
Turning on slugify_html_links will cause the output folders to be `log` and `changelog` instead of `Log` and `Changelog`. On my linux system, this will mean that no notes are included in the feed, because the configured subfolders don't exist.

Same thing with the navbar_links:
``` yaml
navbar_links:
  - name: About
    link: General Information/About ObsidianHtml.html  
  - name: Configurations
    link: Configurations/Configuration Options.html
  - name: News
    link: News.html
```

Even link `News.html` is broken because it only knows `news.html`. This won't be an issue on windows machines, but will be at most other setups.

Not that critical, it's a configure once have forever kind of setting. 

I aim to use slugified links for the docs also, because I have so many spaces and sharing links is just awful. Never thought of slugifying the links. Will do some extra testing soon and apply it to the docs website, then it will get some decent natural testing in.
