### ISSUE TITLE
Building is really slow, and TOC generation did not work properly

### ISSUE THREAD

**Issue by blacklightpy** [obsidian-html/obsidian-html#607]
1. The SECOND PASS HTML stage took 9 minutes for me with all my folders included. I have a vault with around 860 notes.
Only including one folder with about 61 notes took less than 15 seconds, I guess.
I found a similar issue at #560, but apparently it was made faster towards the end.
2. Also, the TOC generation feature did not work even though I had `add_toc_when_missing: true` set. Apparently, it had nothing to do with not starting the headings with h1, since few pages starting with h4 had TOC generated. I can't figure out a pattern, because the pages in the root folder do not have a TOC, and some pages inside folders have TOC. Then again there are some pages inside folders which do not have a TOC.

My vault is available [here](https://github.com/blacklightpy/Obsidian-Notes-Backup).

Examples without TOC:

> 1. /World Building/Science and Engineering/Information and Communication Technology/DevOps/Blue Green Deployment.html
> 2. /Chroma Subsampling.html

Examples with TOC:

> 1. /World Building/Creativity and Arts/Colour Theory/Colour Modelling/Colour Spaces/CIE 1931 XYZ Colour Space.html

I'm using the latest release from `pip`, which is `3.4.1`. I used the config.yml generated from `obsidianhtml run` and modified it as shown below.

```YAML
# config.yml

#obsidian_folder_path_str: D:/Backup/Common Folder/02 Areas/Personal/Self Study/Obsidian Notes
obsidian_entrypoint_path_str: D:/Backup/Common Folder/02 Areas/Personal/Self Study/Obsidian Notes/home.md
log_output_folder_path_str: output/log
included_folders: []
exclude_glob:
  - /.obsidian
  - /.trash
  - /.DS_Store
  - /.git
max_note_depth: -1
copy_vault_to_tempdir: true
copy_vault_to_tempdir_method: default
copy_vault_to_tempdir_follow_copy: true
included_file_suffixes:
  - jpg
  - jpeg
  - gif
  - png
  - bmp
  - svg
  - mp4
  - webm
  - ogv
  - mov
  - mkv
  - mp3
  - wav
  - m4a
  - ogg
  - 3gp
  - flac
  - pdf
video_format_suffixes:
  - mp4
  - webm
  - ogv
  - mov
  - mkv
audio_format_suffixes:
  - mp3
  - webm
  - wav
  - m4a
  - ogg
  - 3gp
  - flac
embeddable_file_suffixes:
  - pdf
md_source_host_urls: []
site_name: Jyothish's Knowledgebase
html_url_prefix: ''
html_template_path_str: ''
html_custom_inclusions: []
html_custom_footer_inclusions: []
navbar_links: []
file_exports: []
toggles:
  compile_md: false
  compile_html: true
  strict_line_breaks: false
  force_filename_to_lowercase: true
  process_all: true
  verbose_printout: true
  debug_filetree_keys: false
  extended_logging: false
  allow_duplicate_filenames_in_root: true
  warn_on_skipped_image: true
  no_clean: false
  relative_path_md: true
  relative_path_html: false
  external_blank: false
  preserve_inline_tags: true
  features:
    styling:
      layout: documentation
      header_template: full
      max_note_width: 120rem
      add_dir_list: true
      accent_color: 65, 76, 253
      loading_bg_color: 255, 255, 255
    theme_picker:
      enabled: true
      styling:
        show_icon: true
    code_highlight:
      enabled: true
    mermaid_diagrams:
      enabled: true
    callouts:
      enabled: true
    math_latex:
      enabled: true
    backlinks:
      enabled: true
    embedded_note_titles:
      enabled: true
      hide_on_h1: true
    search:
      enabled: true
      styling:
        show_icon: true
    embedded_search:
      enabled: false
    tags_page:
      enabled: true
      styling:
        show_icon: true
        show_in_note_footer: true
    dataview:
      enabled: false
      folder: obs.html/export
    folder_notes:
      enabled: false
      placement: outside folder
      naming: folder name
    eraser:
      enabled: true
    breadcrumbs:
      enabled: false
    graph:
      enabled: true
      templates:
        - id: 2d
          name: 2d
          path: builtin<2d>
        - id: 3d
          name: 3d
          path: builtin<3d>
      styling:
        show_icon: true
      coalesce_force: '-30'
      show_inclusions_in_graph: true
    rss:
      enabled: false
      host_root: https://localhost:8888/
      styling:
        show_icon: true
      channel:
        title: Notes
        website_link: <https://your website.com>
        description: <your description>
        language_code: en-us
        managing_editor: n/a
        web_master: n/a
      items:
        selector:
          match_keys: []
          exclude_keys: []
          include_subfolders: []
          exclude_subfolders:
            - .git
            - obs.html
          exclude_files:
            - not_created.html
            - index.html
        description:
          selectors:
            - - yaml
              - rss:description
            - - first-paragraphs
              - 2
              - <br/><br/>
            - - first-header
              - 1
        title:
          selectors:
            - - yaml
              - rss:title
            - - first-header
              - 1
            - - path
              - - parent
                - 1
              - '/ '
              - - stem
        publish_date:
          selectors:
            - - yaml
              - rss:publish_date
            - - yaml_strip
              - tags
              - - date/
          iso_formatted: true
          format_string: ''
    create_index_from_dir_structure:
      enabled: false
      verbose: false
      rel_output_path: obs.html/dir_index.html
      styling:
        show_icon: true
      exclude_subfolders:
        - .git
        - __src
        - md
        - obs.html
      exclude_files:
        - .gitignore
        - favicon.ico
        - not_created.html
      homepage_label: index
    create_index_from_tags:
      enabled: false
      verbose: false
      rel_output_path: obs.html/tag_index.md
      homepage_label: index
      use_as_homepage: false
      add_links_in_graph_tree: true
      tags: []
      match_on_inline_tags: false
      styling:
        include_folder_in_link: false
      sort:
        method: none
        key_path: ''
        value_prefix: ''
        reverse: false
        none_on_bottom: true
      exclude_paths:
        - .gitignore
    table_of_contents:
      add_toc_when_missing: true
    side_pane:
      left_pane:
        enabled: true
        width: 16rem
        contents: dir_tree
        content_args:
          rel_path: index.html
          div_selector: .content
          strip_sub_divs:
            - .toc
      right_pane:
        enabled: true
        width: 16rem
        contents: toc
        content_args:
          rel_path: index.html
          div_selector: .content
          strip_sub_divs:
            - .toc
md_folder_path_str: C:/Users/Blacklight/AppData/Local/Temp/obshtml_z8ujj3w6/md
md_entrypoint_path_str: C:/Users/Blacklight/AppData/Local/Temp/obshtml_z8ujj3w6/md/index.md
html_output_folder_path_str: C:/Users/Blacklight/AppData/Local/Temp/obshtml_z8ujj3w6/html
```

**Comment by blacklightpy** [comment]
Added more info.

**Comment by dwrolvink** [comment]
Are you running the current master code, or the latest pypi release?
Not sure the performance improvements are all in the latest release already. 

9 minutes is incredibly long for 600-ish notes. I've run your config on your vault (with compile_md: true) and it took 15 seconds.

If you set:
``` yaml
toggles:
  features:
    side_pane:
      left_pane:
        enabled: false
      right_pane:
        enabled: false
```

How long does it take then?

Regarding the table of contents, there is a (possibly quite badly documented) feature of not generating the TOC if there is only one header in the page, as then the TOC is pointless. I should add a setting for that really to turn that on/off.

Will do that in this issue.
