### ISSUE TITLE
Graph and navbar in minimal

### ISSUE THREAD

**Issue by antivenom03** [obsidian-html/obsidian-html#609]
like the title says, I really like the centered layout of minimal, but I'd like to be able to use the graph/navbar as well as dark mode. toggling the graph on right now adds the button to the bottom of the page, but the graph doesn't actually generate

**Comment by dwrolvink** [comment]
You could set the template to be documentation, and then create the file `custom.css` in the root of your vault:
``` css
#left_pane {
    display: none;
}
#right_pane {
    display: none;
}
#header_flex {
    justify-content: center;
}
#navbar {
    width: fit-content;
}
.container {
    max-width: 70rem !important;
    margin: auto;
}
.container_filler {
    display: none;
}

#left_pane_toggle_nav {
    display: none;
}
#right_pane_toggle_nav {
    display: none;
}
```

Then in your config.yml, add these lines:
``` yaml
html_custom_inclusions:
  - '<link rel="stylesheet" href="/custom.css" />'

file_exports:
  - encoding: utf-8
    src: custom.css
    dst: custom.css
```

Then you will have the documentation layout but without the side panes, and with all the content centered on the page.

Let me know if this works for you / whether you need assistance!
