### ISSUE TITLE
idea: a way to show backlinks to a node/document

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#64]

**Comment by dwrolvink** [comment]
The graph.json is available. Normally it would be nice to add the section in ConvertMarkdownPageToHtmlPage(), but we can't guarantee that the whole graph is available by then.

I guess the cleanest solution would be to:

> At the end of ConvertMarkdownPageToHtmlPage(), save a tuple in a global list: (node_id, html_file_location) and then go through that list **after** all the ConvertMarkdownPageToHtmlPage() calls are done, adding in the backlinks list at the end of the generated files using the now complete pb.network_tree

Requires us only to add a placeholder like {very_unique_backlinks_placeholder} at the end of the content block for each file in ConvertMarkdownPageToHtmlPage() and just skip that whole thing if the config tells us not to create backlinks.

The other option would be to write some extra javascript to query the graph.json, but that is not trivial.

**Comment by dwrolvink** [comment]
working on this

**Comment by dwrolvink** [comment]
This can now be tested. I tested it locally with every combination of these two booleans:

``` yaml
toggles:
  features:
    backlinks:
      enabled: True
    graph:
      enabled: True
```

Default of feature/backlinks is enabled: True, so if it's missing from the config it should be turned on.

**Comment by jcolson** [comment]
also needs
```yml
      coalesce_force: '-200'
```

edit:
working great!

**Comment by dwrolvink** [comment]
ooh right, didn't handle those cases yet
but good that it is working!

**Comment by jcolson** [comment]
ah .. did you rename?

```yml
    graph_view:
      enabled: True           # Include code to build the graph view per page (default: True)
      coalesce_force: '-200'
```

to 
```yml
    graph:
      enabled: True           # Include code to build the graph view per page (default: True)
      coalesce_force: '-200'
```
