### ISSUE TITLE
obsidian chem plugin: smiles formulas don't work

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#673]
The plugin

https://github.com/Acylation/obsidian-chem

uses the smiles standard for showing chemical structures.

**Comment by dwrolvink** [comment]
Alright in master now there is v1 support for smiles.

It is disabled by default, add this to your config after reinstalling the master branch:
``` yaml
toggles:
  features:
    smiles:
      enabled: True
      theme: dark       # dark, light, oldschool, oldschool-dark, solarized, solarized-dark, matrix, github, carbon, cyberpunk, gruvbox, gruvbox-dark
      width: 100%       # XXX%, XXXpx, XXX 
      height: 300px     # XXX%, XXXpx, XXX
```

How it should look:
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/63669297-872d-4999-8924-b6b0b97ad20b)

**Comment by merlinuwe** [comment]
Wao, impressive images ↑. ;-)

Added your 7 lines to the end of config.yml

(.txt is only added for uploading in github)

[config.yml.txt](https://github.com/obsidian-html/obsidian-html/files/11510627/config.yml.txt)

Then I started 

./obsidianhtml convert -f "H:\Syncthing\Obsidian\BBZ\Unterricht CTA SuS\Index.md" -i "C:\Users\uwewe\AppData\Roaming\Python\Python311\Scripts\config.yml"

in Git Bash.

I got this:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/87c59cde-3326-422e-a000-b3a875c04755)

(Is it ok, that this causes the webserver to die?)

started webserver in Git Bash.

`python -m http.server --directory output/html 8888`

(If the 7 lines don't disturb anything, you can consider to add them later as default in config.yml.)

No, this does not work in Google Chrome or Firefox or Edge.

http://localhost:8888/BBZ/Unterricht%20CTA%20SuS/Chemie%20-%20Smile%20Formeln.html

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/67bc967f-47ed-4af7-aef9-a52da3b938ce)

(Tested twice.)

**Comment by dwrolvink** [comment]
Remove this block from your config.yml (or even better, as I said before, remove everything except for custom values):

``` yaml
module_list:
  convert_markdown_to_html: []
  convert_note_to_markdown: []
  finalize:
  - description:
    - Creates the log of which module resources were accessed by which module
    - Requires persistent meta_module of the same name to work!
    method: finalize
    name: resource_logger
    persistent: true
  preparation:
  - description: Merges the user config with default config and runs checks.
    name: process_config
  - description: Determine all paths of interest based on input.
    name: load_paths
  - description: Prepare and export templates used to create html output.
    name: html_templater
    persistent: true
  - name: load_graphers
    persistent: true
  - description:
    - Copy vault to temporary directory, so that we can edit the obsidian notes themselves
      safely.
    - Must be persistent!
    name: copy_vault_to_tempdirectory
    persistent: true
  - description:
    - Ensures the output folders are created
    - Optionally removes previous output if it exists in the target directories
    name: prepare_output_folders
  - description:
    - Basic file listing based on include_folder/exclude_glob combination
    - Further filtering can be done in further modules
    name: get_file_list
  - description:
    - Gets the metadata of each markdown file, and stores it under metadata/<rel_filepath>.json
    name: parse_metadata
  - description:
    - Filter out markdown files that do not comply to certain metadata requirements
    name: filter_on_metadata
```

That should resolve your error from the terminal.
If you are running the latest master version I see no reason why this shouldn't work for you.
