### ISSUE TITLE
Bug in commit bc56f42 / PR GH-684: header-inclusions will include entire note, instead of only the header's content 

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#686]
Hello, 

This pertains commit bc56f42 and subsequent commits, and thus also GH-684. I have not had the time to find the specific issue yet, but want to put this onto the radar.

I am experiencing a bug when checking out bc56f42. This is not related to my own modifications, but occurs when using the "official" main branch as well.

**Overview**:  

    e931daa: works
    a18aa41: works
    0061778: prints the entire note when embedding sections
    	bc56f42: first commit which generates this issue.
    	5c940b9: as a child of bc56f42, this obviously also fails

The issue:

assume this parent note `019-ObsHTML_EmbeddedTitleStripping_Main`:

```md
---
AutoNoteMover: disable
creation date: "2023-03-23 17:55"
modification date: "2023-04-18 21:49"
tags: programming/bug/triage 
---

# Header

1: This is a main note, and I want to embed text on a new line:  
![[019-ObsHTML_EmbeddedTitleStripping_Child#A Section]]|||

2: This is a main note, and I want to embed text inline which is ![[019-ObsHTML_EmbeddedTitleStripping_Child#A Section]]|||

3: Indented:  
		![[019-ObsHTML_EmbeddedTitleStripping_Child#A Section]]|||

# Full-Note

4: This is a main note, and I want to embed text on a new line:  
![[019-ObsHTML_EmbeddedTitleStripping_Child]]|||

5: This is a main note, and I want to embed text inline which is ![[019-ObsHTML_EmbeddedTitleStripping_Child]]|||

6: Indented  
		![[019-ObsHTML_EmbeddedTitleStripping_Child]]|||


```

and this child note `019-ObsHTML_EmbeddedTitleStripping_Child.md`:

```md
---
AutoNoteMover: disable
creation date: "2023-03-23 17:55"
modification date: "2023-05-17 12:15"
tags: programming/bug/triage 
---

This is a child note

# A Section

containing words

# A second section

**containing different words**
```

Converting via 

`obsidianhtml convert -i "D:\Dokumente neu\000 AAA Dokumente\000 AAA HSRW\General\AHK scripts\Projects\Finished\ObsidianScripts\OHTMLconfig_temp.yaml"`

with YAML-contents

```yaml
# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
# md_folder_path_str:  'output/md'
# Number of links a note can be removed from the entrypoint note
# -1 for no max depth
# 0 means only the entrypoint note is processed
# 1 means only direct children are processed (and the entrypoint of course)
# and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
obsidian_entrypoint_path_str: 'D:\Dokumente neu\Obsidian NoteTaking\The Universe\019-Bugtesting-Subvault\019-ObsHTML_EmbeddedTitleStripping_Main.md'
max_note_depth: 15
# preserve_inline_tags: False
toggles:
# When true, Obsidianhtml will not add three spaces at the end of every line
  strict_line_breaks: True
# compile_html: False
  features:
    embedded_note_titles:
      enabled: False
```

will produce this output:

```md
---
AutoNoteMover: disable
creation date: 2023-03-23 17:55
modification date: 2023-04-18 21:49
obs.html.data:
  inclusion_references:
  - 019-obshtml_embeddedtitlestripping_child.md
tags:
- programming/bug/triage
---

# Header

1: This is a main note, and I want to embed text on a new line:  


This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

2: This is a main note, and I want to embed text inline which is 

This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

3: Indented:  
		

This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

# Full-Note

4: This is a main note, and I want to embed text on a new line:  


This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

5: This is a main note, and I want to embed text inline which is 

This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

6: Indented  
		

This is a child note

# A Section

containing words

# A second section

**containing different words**
|||
```

As you can see, the embeds in the "header"-section (cases 1-3) still contain the entire text of the embedded note, instead of only the contents of section `A section`. The `|||` mark the first character after the closing brackets of `![[inclusion.md]]`.

Comparing to the output generated with same inputs when checking out commit a18aa41 / PR GH-682, we can see that the contents before the header, as well as the contents of the second first-level header `# A second section` are now successfully left out:

```md
---
AutoNoteMover: disable
creation date: 2023-03-23 17:55
modification date: 2023-04-18 21:49
obs.html.data:
  inclusion_references:
  - 019-obshtml_embeddedtitlestripping_child.md
tags:
- programming/bug/triage
---

# Header

1: This is a main note, and I want to embed text on a new line:  

# A Section
containing words

|||

2: This is a main note, and I want to embed text inline which is 
# A Section
containing words

|||

3: Indented:  
		
# A Section
containing words

|||

# Full-Note

4: This is a main note, and I want to embed text on a new line:  


This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

5: This is a main note, and I want to embed text inline which is 

This is a child note

# A Section

containing words

# A second section

**containing different words**
|||

6: Indented  
		

This is a child note

# A Section

containing words

# A second section

**containing different words**
|||
```

I hope these information are sufficient - I will be able to provide further if required. 

Thank you,  
Sincerely,  
~Gw
