### ISSUE TITLE
CSS cosmetics for checklists

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#708]
I have a checklist

```

- [ ] Individuelles Anschreiben auf Basis des letzten Links mit aktuellem Datum
	- [x] Schreiben im Deutschunterricht zum Ende des 1. Ausbildungsjahres formulieren 
	- [ ] Korrektur durch den Deutschlehrer
	- [ ] Umsetzung in Word im Fach LABV INF
	- [ ] Konvertierung in eine einzige, kleine .pdf-Datei
	- [ ] Hochladen jeder einzelnen Bewerbung in Moodle M3
- [ ] Lebenslauf mit aktuellem Datum
- [ ] Aktuelle Praktikumsbescheinigungen als Kopien
- [ ] Die letzten beiden Schulzeugnisse als Kopien
- [ ] Schulische Formblätter zum Nachweis des Versicherungsschutzes
- [ ] Besondere Qualifikationen, ehrenamtliches Engagement, sportliche Leistungen, Zertifikate von Volkshochschulen (VHS) etc.

```

which is shown in Obsidian:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/c74fa98a-2cf2-4d5a-a477-04a5139e4b0a)

wich is shown in the output:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/e3eca286-6764-4b7e-bc2d-1bcf1704086a)

It needs some styling (as well as other elements).

**Comment by dwrolvink** [comment]
Hmm, it is missing the `x` in the markdown in the output, that might be an issue for checklists.

**Comment by merlinuwe** [comment]
No, I added the x _later_ (after exporting the output) to show how it can look.

**Comment by dwrolvink** [comment]
What do you think about this style? (Not yet pushed)

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/7745f32c-2148-4f90-b921-3b4015c97b57)

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/e3e3d3e3-19bf-496d-a810-8734b5296015)

**Comment by merlinuwe** [comment]
Much better. But a checkmark would be more obvious for black themes. Nothing to confuse with.

https://de.wikipedia.org/wiki/H%C3%A4kchen_(Schriftzeichen)

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/8ac254b1-eed1-4664-9a89-45890427e5ba)

**Comment by dwrolvink** [comment]
Agree that the dark button was a bit ambiguous, especially if everything is checked.
I settled on this, based on my style sensibilities, I think this is a nice middle ground:

![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/80f20e2d-1b2e-4e46-96df-e6758d7b2a7c)
![image](https://github.com/obsidian-html/obsidian-html/assets/30291690/079792ad-a336-4d89-8576-a24f51541417)

I've pushed the changed so you can check it out. 
Relevant css:

``` css
/* global */
.checklist-item {
    list-style: none;
}

.checklist-item .checked {
    display: inline-block;
    background-color: var(--color-accent2);
    color: var(--callout-color);
    padding-left: 0.25rem;
    padding-right: 0.15rem;
    border-radius: 0.2rem;
    line-height: 1.0rem;
    font-size: 0.7rem;
    margin-right: 0.6rem;
}

.checklist-item .unchecked {
    display: inline-block;
    margin-right: 0.6rem;
}
/* theme (overwrites global) */
.theme-obs-dark .checklist-item .unchecked {
    opacity: 0.5;
}

.theme-obs-light .checklist-item .checked {
    background-color: #828282;
    color: white;
}
```

Did not check the interaction of this change with other parts of the code, but it only applies to list items, so if this breaks anything else, it should be limited.
