### ISSUE TITLE
Table has capital Letters For Every Word

### ISSUE THREAD

**Issue by merlinuwe** [obsidian-html/obsidian-html#709]
I have a table:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/6224d9d7-580e-440d-a692-d873250b5fc2)

which looks so:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/0b95146f-0cb7-494c-af61-f1a328e69a62)

In the output it looks so:

![image](https://github.com/obsidian-html/obsidian-html/assets/4138869/285b7c67-4c63-496b-8871-7590f694b738)

Yes, a styling issue, too, but in the header art capital Letters For Every Word.

correct: Bedeutung in der Chemie
wrong: Bedeutung In Der Chemie

**Comment by dwrolvink** [comment]
1. Create a file called `custom.css` in the root of your vault, fill it with this:
``` css
th {
    text-transform: none;
}
```

2. Add this to your `config.yml`:
``` yaml
html_custom_inclusions:
  - '<link rel="stylesheet" href="/custom.css" />'

file_exports:
  - encoding: utf-8
    src: custom.css
    dst: custom.css
```

> You can change the place you put `custom.css`, as long as you also edit the paths in the config.yml

> You might need to ctrl+shift+R reload the page, before the changes are processed as CSS sometimes is pretty well cached.
It might also be needed to open http://localhost:8000/custom.css (port may also be 8080, look at the command you use) and ctrl+shift+R on that file too.

I could probably remove the `text-transform: capitalize` from the main CSS, but given your requests, I think it would be good if you set up a custom css anyways, probably going to be useful at some point.
