### ISSUE TITLE
Configfiles with encoding 'UTF-8' are parsed correctly even if the path does contain invalidly-encoded chars

### ISSUE THREAD

**Issue by Gewerd-Strauss** [obsidian-html/obsidian-html#769]
Hello,

I am currently catching up with the v.4.X branch, and I am noticing sudden issues with feeding `utf-16-LE`-encoded configfiles.

_Background_:
I generate the config-file in utf-8, and have done so _forever_, even if they contain invalidating characters, e.g. `äöü`. Of course, this results in a garbled file:

```yaml
obsidian_entrypoint_path_str: 'D:\Dokumente neu\Obsidian NoteTaking\The Universe\200 University\06 Interns and Unis\BE28 Internship Report\Methods\Exp2 Gr�nfl�chenanalyse.md'
```

The intended string would be:

```yaml
obsidian_entrypoint_path_str: 'D:\Dokumente neu\Obsidian NoteTaking\The Universe\200 University\06 Interns and Unis\BE28 Internship Report\Methods\Exp2 Grünflächenanalyse.md'
```

Miraculously, this has never been an issue. I have been saving files in garbled `utf-8` since the start, and it never had issues reading the config file. _Obviously, this makes absolutely no sense_. To ensure this does not become an issue, I planned on saving the config as `utf-16-le` to properly encode the paths, as well as any other Umlaute. 
So, I saved the config-file as `utf-16-le`. This is where the trouble began. I have attached the contents of the config-file I am writing to disk at the end of this post.

---

_Suggestion_:
The encoding of a fed config-file should be detectable, and used properly to load the file successfully. Cursory search shows there are several packages that allow encoding-detection, namely `chardet` and potentially `charset-normaliser` which could be used to detect the encoding required for a successfull read.
I have not had the time to go search for a best approach yet, but will hopefully get a look at it soon.

Once the correct encoding is retrieved, the config file should be easily read correctly.

---

I hope this is enough info to get a conversation going for now. Privately I am inclined to just hard-code a trycatch for the encoding I am using until I figure out how to determine it successfully (but I have not yet checked if that works even. If it doesn't and I fail to fix the issues, I will have to remain on my old version for now, as I cannot afford a broken instance right now really.)

Is there anything I missed with regards to this issue? Any reason why encoding is not checked as of yet? 

Thank you.
Sincerly,
~Gw

---

```yaml
# Input and output path of markdown files
# This can be an absolute or a relative path (relative to the working directory when calling obsidianhtml)
# Use full path or relative path, but don't use ~/
# md_folder_path_str:  'output/md'
# Number of links a note can be removed from the entrypoint note
# -1 for no max depth
# 0 means only the entrypoint note is processed
# 1 means only direct children are processed (and the entrypoint of course)
# and so forth. NOTE: DOES NOT APPLY TO INCLUSIONS!
obsidian_entrypoint_path_str: 'D:\Dokumente neu\Obsidian NoteTaking\The Universe\200 University\06 Interns and Unis\BE28 Internship Report\Methods\Exp2 Grünflächenanalyse.md'
# module_data_folder: 'output/mod'
max_note_depth: 15
# preserve_inline_tags: False
copy_vault_to_tempdir: True
exclude_glob:
  - ".git"
  - ".obsidian"
  - ".trash"
  - ".vscode"
  - ".DS_Store"
  - "002 templates"
  - ".Rproj.user"
  - "renv"
exclude_subfolders:
  - ".git"
  - ".obsidian"
  - ".trash"
  - ".vscode"
  - ".DS_Store"
  - "002 templates"
  - ".Rproj.user"
  - "renv"














toggles:
# When true, Obsidianhtml will not add three spaces at the end of every line
  strict_line_breaks: True
  wrap_inclusions: True
# compile_html: False
  features:
    embedded_note_titles:
      enabled: False
# big css/js files to download + data to download
# and read in that scales with the size of the site.
    graph:
      enabled: False
      show_inclusions_in_graph: False
    search:
      enabled: False
  
# big css/js files to download.
    mermaid_diagrams:
      enabled: False
    math_latex:
      enabled: False
  
# small, css based features.
    code_highlight:
      enabled: False
    callouts:
      enabled: False
```
