### ISSUE TITLE
feature: enable method to sort nodes/docs by frontmatter `timestamp` data

### ISSUE THREAD

**Issue by jcolson** [obsidian-html/obsidian-html#88]
enable a feature which allows users to choose frontmatter timestamp data to use for sorting documents in the entrypoint tags method (or anywhere lists of documents are generated?)

will require using different timestamp methods (such as {{date:YYYY-MM-DD}}T{{time:HH:mm:ssZ}} or {{date}} ... etc)

ex:

```md
---
created: 2022-01-15T15:26:07+00:00
updated: 2022-02-06T22:59:26+00:00
---
```

```md
---
created: {{date:YYYY-MM-DD}}T{{time:HH:mm:ssZ}}
updated: {{date:YYYY-MM-DD}}T{{time:HH:mm:ssZ}}
---
```

```md
---
tags:
- date/{{date}}
---
```

**Comment by dwrolvink** [comment]
Let's add this in and then do a full testing round.

Then I can make a new pypi package, because the last one is awfully outdated.

At that point I'll also make a branch with the pypi version as a tag, and then we can just continue in master without issue, solving #34

**Comment by dwrolvink** [comment]
Gonna work on it today. I also got an idea for how to do the original "sort on last created". Would just entail getting the creation times from the original folder before copying it over. 

Thinking of changing the settings to something like this:
``` yaml
    create_index_from_tags:
      enabled: True
      add_links_in_graph_tree: True
      tags:
        - my_tag
      sort:
        method: 'creation_time'   # <creation_time, tag_prefix, keyvalue, none>
        order: 'ascending'        # <ascending, descending>
        tag_prefix: ''            # e.g. 'date/'
        key_value: ''             # e.g. 'created'
```

**Comment by jcolson** [comment]
Instead of tag_prefix call it key_prefix (or something), as #tags are something different in markdown.  Tags can be included anywhere as WELL as in the key value for tags: in the frontmatter

**Comment by dwrolvink** [comment]
Hmm it's still too complex in my head. I've managed to simplify it to this:

``` yaml
    create_index_from_tags:
      enabled: True
      add_links_in_graph_tree: True
      tags:
        - my_tag
      sort:
        method: 'key_value'   # <creation_time, key_value, none>
        order: 'ascending'        # <ascending, descending>
        key_path: 'tags'             # empty for top level, use ':' to go down multiple levels
        value_prefix: 'date/'    # in case of multiple values under key_path, match on this prefix, and then remove prefix
```

**sort on tags:date/**
``` yaml
method: 'key_value'
key_path: tags
value_prefix: date/
```

**sort on updated**
``` yaml
method: 'key_value'  
key_path: 'updated'
value_prefix: ''
```

Pseudo code:
``` yaml
# get the value of the key that we want to sort on
value = get_val_from_frontmatter(key_path.split(':'))

# resultant value is a list, use value_prefix to select 1 item in the list, remove the prefix, then set that as the sort value
if isinstance(value, list):
  listitems = match_items_and_remove_prefix(value, value_prefix)
  if len(listitems) = 0:
    continue
  elif len(listitems) > 1:
     raise Oops(ambiguous sort value, too many values found)
  set_sort_value(listitems[0])
  continue

if isinstance(value, dict):
  raise Oops(can't sort on dict)   

if isinstance(value, bool):
  set_sort_value(int(value))
  continue

# what remains is str and int
if isinstance(value, str) and value_prefix != '':
  # if type = str and value_prefix is set, remove the prefix
  value = remove_prefix(value, value_prefix)

set_sort_value(value)
```

**Comment by dwrolvink** [comment]
Okay, these are the current settings now:

``` yaml
    create_index_from_tags:
      enabled: False
      add_links_in_graph_tree: True
      tags: []
      sort:
        method: 'none'          # <key_value, none>
        key_path: ''            # empty for top level, use ':' to go down multiple levels
        value_prefix: ''        # in case of multiple values under key_path, match on this prefix, and then remove prefix
        reverse: false          # false/true reverses output
        none_on_bottom: true    # will put notes at the bottom that do not have the sort key, otherwise at the top
```

I managed to sort on tags:date/{date} by:
``` yaml
toggles:
  features:
    create_index_from_tags:
      sort:
        method: 'key_value'
        key_path: 'tags'
        value_prefix: 'date/' 
```
and sort on `sort: 1`, `sort: 2`, etc by:
``` yaml
toggles:
  features:
    create_index_from_tags:
      sort:
        method: 'key_value'
        key_path: 'sort'
        value_prefix: ''
```

`reverse` replaced ascending/descending, as that is what sorted uses, and with dates ascending is always kind of confusing anyways. If the order is wrong, flip the switch.

`none_on_bottom` is kind of self explanatory. If no value is found for the sort key, where do you want the notes then? default at the bottom.

**Comment by dwrolvink** [comment]
next up the created_time, and then this should be done!
(aside from possible bugs)

**Comment by dwrolvink** [comment]
Okay, so apparently getting the creation time of files in Linux, is reallly difficult for some reason. Just made that option not pickable when you aren't on Windows. It might work for OSX, but I can't test that, so I disabled it there too.

``` yaml
sort:
  method: modified_time
```
is all you need to have them sorted on when they are modified. 

on another note: the regression tests just caught some weird edge case that I would've never noticed otherwise! Happy that all those hours are paying off now :laughing:  tedious work (but pushing bugs into the code constantly was getting old too).

with this change this issue should be finished, but I'll leave it open for if you want to test the OSX case for created_time, @jcolson. Otherwise we'll leave that for if someone shoots in a usecase for it.

**Comment by jcolson** [comment]
Yeah, I'll play with it!

**Comment by jcolson** [comment]
ok, first thing i notice is I no longer have any images in the resultant output now.  and lots of warnings:

```
> COPYING VAULT /Volumes/GoogleDrive/My Drive/Obsidian/Jay's Notebook TO /var/folders/d6/9gcvqr2929j699j8xr95qtk40000gn/T/tmpv2qitcqx < DONE
> CLEARING OUTPUT FOLDERS
> CREATING OUTPUT FOLDERS
> COMPILING MARKDOWN FROM OBSIDIAN CODE (/private/var/folders/d6/9gcvqr2929j699j8xr95qtk40000gn/T/tmpv2qitcqx/dontparse)
> COMPILING HTML FROM MARKDOWN CODE (/Users/jcolson/src/personal/DragonHearts/output/md/__tags_index.md)
File /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Pasted image 20220207171543.png not located, so not copied.
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Pasted image 20220207171543.png treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
File /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image1.png not located, so not copied.
File /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image2.jpeg not located, so not copied.
File /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image3.jpeg not located, so not copied.
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image1.png treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image2.jpeg treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image3.jpeg treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
File /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image4.png not located, so not copied.
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/media/D_D-DragonHeart-Dec-15,-2021-18-31-57-GMT-image4.png treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
File /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Vormorn_token.png|200 not located, so not copied.
File /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Vormorn.jpg|300 not located, so not copied.
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Vormorn_token.png|200 treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Vormorn.jpg|300 treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
File /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Hymey.jpg|300 not located, so not copied.
File /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Hymey.pdf not located, so not copied.
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Hymey.jpg|300 treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Hymey.pdf treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
File /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Quinn_Lioncourt.pdf not located, so not copied.
/opt/homebrew/lib/python3.9/site-packages/obsidianhtml/__init__.py:198: UserWarning: Image /Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Quinn_Lioncourt.pdf treated as external and not imported in html
  warnings.warn(f"Image {str(full_link_path)} treated as external and not imported in html")
> DONE
```

**Comment by jcolson** [comment]
looking at one of the paths:
`/Users/jcolson/src/personal/DragonHearts/output/md/TTRPG/DragonHeart/Pasted image 20220207171543.png not located, so not copied.`

it SHOULD be 
`/Users/jcolson/src/personal/DragonHearts/output/md/media/Pasted image 20220207171543.png not located, so not copied.`

but the entire `media/` directory is not being copied into the output/md directory during the markdown phase.

sorry, don't have time this morning to look into it further ... running out the door

**Comment by dwrolvink** [comment]
Hmm not really sure how sort settings would affect the copying of images.
Is this something that only happens with sort: method: modified_time? or any sort method other than none? or does it always happen with create_index_from_tags: enabled: True?

**Comment by dwrolvink** [comment]
Oh, I think I'm on track of something, give me a sec

**Comment by dwrolvink** [comment]
Alright, as far as my testing goes this should fix it.

What the issue was:
I did some complicated file tree overwriting because the tag index could not be written to the user vault. 

There is testing all over the place, and `.relative_to()` statements that break if an obsidian file is not in the obsidian folder. So I wrote the index to the md_folder and then just wrote down somewhere that process_all was needed to use this feature, but I never added tests on it, and I think I broke the process_all feature too anyways. 

But now that the copy to temp dir feature is here, I could make the code way more sensible by just writing the tag index to the temp obsidian folder. And this time I made a test that will tell the user to turn on the copy to temp dir feature if they want to use this feature. 

Perhaps in the future we can make it work without that feature, but the aforementioned difficulty is that the entire code base makes certain assumptions, and those all need to be rewritten/rethinked to make such a change work.

Anyways, if you make sure the copy to temp dir feature is turned on, this feature should work now.

**Comment by jcolson** [comment]
maybe i'm misconfigured?  they key_value method of sorting doesn't seem to be picking up my key.  without looking at the code yet, it may be the date format?

```
      sort:
        method: 'key_value'     # <key_value, creation_time, modified_time, none>    ! created_time not available on Linux!
        key_path: 'created'            # empty for top level, use ':' to go down multiple levels
        value_prefix: ''        # in case of multiple values under key_path, match on this prefix, and then remove prefix
        reverse: false          # false/true reverses output
        none_on_bottom: true    # will put notes at the bottom that do not have the sort key, otherwise at the top
```

frontmatter:

```
---
title: Feb 10, 2022 - Session
created: 2022-02-10T20:06:50+00:00
tags: [ sco-session ]
updated: 2022-02-10T21:27:26+00:00
---
```

sort values debug:

```
                Matched note Jolo Brekk.md on tag dh-character
                        Sort value of note Jolo Brekk.md is None
                Matched note Blackened liquid glassy metallic blade.md on tag dh-item
                        Sort value of note Blackened liquid glassy metallic blade.md is None
                Matched note Lion's Pride.md on tag dh-npc
                        Sort value of note Lion's Pride.md is None
                Matched note Valley Fighting Pit.md on tag dh-location
                        Sort value of note Valley Fighting Pit.md is None
                Matched note Vormorn.md on tag dh-character
                        Sort value of note Vormorn.md is None
                Matched note Silver Claw.md on tag dh-npc
                        Sort value of note Silver Claw.md is None
                Matched note Jan 12, 2022 - Session 1.md on tag dh-session
                        Sort value of note Jan 12, 2022 - Session 1.md is None
                Matched note The Forger.md on tag dh-npc
                        Sort value of note The Forger.md is None
                Matched note Iron the Bonker.md on tag dh-npc
                        Sort value of note Iron the Bonker.md is None
                Matched note The Crying Pony.md on tag dh-location
                        Sort value of note The Crying Pony.md is None
                Matched note Azutrix.md on tag dh-npc
                        Sort value of note Azutrix.md is None
                Matched note Snack Master.md on tag snack-master
                        Sort value of note Snack Master.md is None
                Matched note Sedwig.md on tag dh-npc
                        Sort value of note Sedwig.md is None
                Matched note Gatekeepers.md on tag dh-npc
                        Sort value of note Gatekeepers.md is None
                Matched note Agathrax.md on tag dh-npc
                        Sort value of note Agathrax.md is None
                Matched note Mossy Cove.md on tag dh-location
                        Sort value of note Mossy Cove.md is None
                Matched note Jan 15, 2022 - Downtime Session 1.1.md on tag dh-session
                        Sort value of note Jan 15, 2022 - Downtime Session 1.1.md is None
                Matched note Feb 7, 2022 - Downtime Session 2.1.md on tag dh-session
                        Sort value of note Feb 7, 2022 - Downtime Session 2.1.md is None
                Matched note Jan 24, 2022 - Session 2.md on tag dh-session
                        Sort value of note Jan 24, 2022 - Session 2.md is None
                Matched note Devil's Cove.md on tag dh-location
                        Sort value of note Devil's Cove.md is None
                Matched note Moradin.md on tag dh-npc
                        Sort value of note Moradin.md is None
                Matched note Barnabus The Churned.md on tag dh-npc
                        Sort value of note Barnabus The Churned.md is None
                Matched note Kraz Lagan the Menacing.md on tag dh-npc
                        Sort value of note Kraz Lagan the Menacing.md is None
                Matched note Rothorn.md on tag dh-npc
                        Sort value of note Rothorn.md is None
                Matched note The Circle.md on tag dh-npc
                        Sort value of note The Circle.md is None
                Matched note DH DM.md on tag dh-character
                        Sort value of note DH DM.md is None
                Matched note Dec 15, 2021 - Session 0.md on tag dh-session
                        Sort value of note Dec 15, 2021 - Session 0.md is None
                Matched note The Old Scar.md on tag dh-location
                        Sort value of note The Old Scar.md is None
                Matched note Quinn Lioncourt.md on tag dh-character
                        Sort value of note Quinn Lioncourt.md is None
                Matched note Bloodbear Clan.md on tag dh-npc
                        Sort value of note Bloodbear Clan.md is None
                Matched note Green Staff.md on tag dh-item
                        Sort value of note Green Staff.md is None
                Matched note Zigmond.md on tag dh-npc
                        Sort value of note Zigmond.md is None
                Matched note Blackscar.md on tag dh-npc
                        Sort value of note Blackscar.md is None
                Matched note Hannat.md on tag dh-location
                        Sort value of note Hannat.md is None
```
